const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const locale=document.documentElement.lang.startsWith('en')?'en':document.documentElement.lang.startsWith('es')?'es':'pt';
const view=document.body.dataset.view||'home';
const intlLocale=locale==='en'?'en-US':locale==='es'?'es-ES':'pt-BR';
const words={pt:{today:'HOJE',tomorrow:'AMANHÃ',sources:'Todas as fontes',found:'publicações encontradas',latest:'Atualizado',cached:'Última cópia disponível',available:'disponível',unavailable:'indisponível',lastGame:'ÚLTIMO JOGO',live:'AO VIVO',scheduled:'NA AGENDA',next:'PRÓXIMO JOGO',where:'ONDE',lineup:'VER ESCALAÇÃO E PALPITES ↓',details:'VER DETALHES →',days:'DIAS',hours:'HORAS',minutes:'MIN',seconds:'SEG',moreGroups:'CARREGAR MAIS GRUPOS ↓'},en:{today:'TODAY',tomorrow:'TOMORROW',sources:'All sources',found:'stories found',latest:'Updated',cached:'Latest available copy',available:'available',unavailable:'unavailable',lastGame:'LAST MATCH',live:'LIVE',scheduled:'UPCOMING',next:'NEXT MATCH',where:'VENUE',lineup:'LINEUPS AND PREDICTIONS ↓',details:'VIEW DETAILS →',days:'DAYS',hours:'HOURS',minutes:'MIN',seconds:'SEC',moreGroups:'LOAD MORE GROUPS ↓'},es:{today:'HOY',tomorrow:'MAÑANA',sources:'Todas las fuentes',found:'publicaciones encontradas',latest:'Actualizado',cached:'Última copia disponible',available:'disponible',unavailable:'no disponible',lastGame:'ÚLTIMO PARTIDO',live:'EN VIVO',scheduled:'PRÓXIMAMENTE',next:'PRÓXIMO PARTIDO',where:'LUGAR',lineup:'ALINEACIONES Y PRONÓSTICOS ↓',details:'VER DETALLES →',days:'DÍAS',hours:'HORAS',minutes:'MIN',seconds:'SEG',moreGroups:'CARGAR MÁS GRUPOS ↓'}};
const t=key=>words[locale][key]||words.pt[key]||key;
const say=(pt,en,es)=>locale==='en'?en:locale==='es'?es:pt;
function storedSeen(){try{const v=JSON.parse(localStorage.getItem('nrn-seen')||'[]');return Array.isArray(v)?v:[]}catch{return []}}
const initial=JSON.parse($('#nrn-initial-data')?.textContent||'{"items":[]}');
const state={news:(initial.items||[]).sort((a,b)=>(Date.parse(b.date)||0)-(Date.parse(a.date)||0)),players:[],polls:[],pollRanks:{},predictionRanks:{},scoreDrafts:{},groups:[],groupsCursor:null,groupsMore:false,matches:[],matchOpinions:{predictions:[],ratings:[]},opinionsLoaded:false,shownNews:6,shownPlayers:6,poll:'melhor-2026-09',selected:null,focusedMatch:null,ratingMatch:null,lastKickoffRefresh:0,goalSound:localStorage.getItem('nrn-goal-sound')==='on',seen:new Set(storedSeen())};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fold=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const formatDate=s=>{const d=new Date(s);return Number.isNaN(+d)?String(s||'Agora'):new Intl.DateTimeFormat(intlLocale,{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(d)};
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3200)}
function setDialog(id,open=true){const d=$(id);if(open&&!d.open)d.showModal();if(!open&&d.open)d.close()}
$$('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#today').textContent=new Intl.DateTimeFormat(intlLocale,{weekday:'long',day:'2-digit',month:'long'}).format(new Date()).toUpperCase();
function setMenu(open){const nav=$('#navigation'),backdrop=$('#nav-backdrop');nav.classList.toggle('open',open);$('#menu').setAttribute('aria-expanded',String(open));const more=$('#mobile-more');if(more)more.setAttribute('aria-expanded',String(open));if(backdrop)backdrop.hidden=!open;document.body.classList.toggle('menu-open',open)}
$('#menu').onclick=()=>setMenu(!$('#navigation').classList.contains('open'));
if($('#mobile-more'))$('#mobile-more').onclick=()=>setMenu(!$('#navigation').classList.contains('open'));
if($('#nav-backdrop'))$('#nav-backdrop').onclick=()=>setMenu(false);
$$('#navigation a').forEach(a=>a.onclick=()=>setMenu(false));
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&$('#navigation').classList.contains('open'))setMenu(false)});
const dockLinks=$$('.mobile-dock a');
function syncDock(){const routeDock={home:'inicio',news:'noticias',matches:'jogos',community:'comunidade'},points=[['inicio','inicio'],['noticias','noticias']],fixed=routeDock[view];let active=fixed||'more';if(view==='home')for(const [id,key] of points){const section=$('#'+id);if(section&&section.offsetTop<=scrollY+160)active=key}dockLinks.forEach(link=>link.classList.toggle('is-active',link.dataset.dock===active));if($('#mobile-more'))$('#mobile-more').classList.toggle('is-active',active==='more')}
dockLinks.forEach(link=>link.addEventListener('click',()=>{dockLinks.forEach(item=>item.classList.toggle('is-active',item===link));if($('#mobile-more'))$('#mobile-more').classList.remove('is-active')}));
let dockFrame;addEventListener('scroll',()=>{if(dockFrame)return;dockFrame=requestAnimationFrame(()=>{dockFrame=0;syncDock()})},{passive:true});addEventListener('hashchange',syncDock);syncDock();
const routePaths={pt:{news:'/noticias',matches:'/jogos',community:'/comunidade'},en:{news:'/en/news',matches:'/en/matches',community:'/en/community'},es:{news:'/es/noticias',matches:'/es/partidos',community:'/es/comunidad'}};
$('#search-jump').onclick=()=>{if(!['home','news'].includes(view)){location.assign(routePaths[locale].news);return}$('#noticias').scrollIntoView();setTimeout(()=>$('#query').focus(),450)};
function playIntro(){const intro=$('#intro');if(!intro||matchMedia('(prefers-reduced-motion: reduce)').matches)return;intro.hidden=true;void intro.offsetWidth;intro.hidden=false;clearTimeout(playIntro.timer);playIntro.timer=setTimeout(()=>intro.hidden=true,900)}
if(view==='home')requestAnimationFrame(playIntro);
$('#replay').onclick=playIntro;
function media(n,hero=false){let src=n.image||'';try{const u=new URL(src);if(u.protocol!=='https:')src='';else if(['admin.cnnbrasil.com.br','a.espncdn.com'].includes(u.hostname))src='/media?src='+encodeURIComponent(src)}catch{src=''}return '<div class="photo-frame'+(hero?' hero-photo':'')+'">'+(src?'<img '+(hero?'loading="eager" fetchpriority="high"':'loading="lazy"')+' decoding="async" width="840" height="500" src="'+esc(src)+'" data-original="'+esc(n.image)+'" alt="'+esc(n.imageAlt||n.title)+'">':'<span class="photo-unavailable">Fotografia não fornecida pela fonte</span>')+'</div><small>'+esc(n.imageCredit||n.source)+'</small>'}
const newsPath=n=>'/noticia/'+String(n.title||'noticia').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,90);
function newsCard(n){return '<article class="news-card"><a href="'+esc(newsPath(n))+'"><div class="news-media">'+media(n)+'</div><div class="news-meta"><b>'+esc(n.source)+'</b><time>'+esc(formatDate(n.date))+'</time></div><h3>'+esc(n.title)+'</h3><span class="read-source">'+say('Ver página da notícia →','Open story page →','Ver página de la noticia →')+'</span></a><button class="share-news" data-link="'+esc(location.origin+newsPath(n))+'" data-title="'+esc(n.title)+'">'+say('Compartilhar ↗','Share ↗','Compartir ↗')+'</button></article>'}
function filteredNews(){let rows=state.news.filter(n=>!$('#query').value||fold(n.title+' '+n.source).includes(fold($('#query').value))).filter(n=>!$('#source').value||n.source===$('#source').value);rows.sort((a,b)=>{const date=(Date.parse(b.date)||0)-(Date.parse(a.date)||0);return $('#sort').value==='photos'?Number(!!b.image)-Number(!!a.image)||date:date});return rows}
function renderNews(){const rows=filteredNews(),shown=rows.slice(0,state.shownNews);$('#feed').innerHTML=shown.length?shown.map(newsCard).join(''):'<div class="empty">Nenhuma notícia encontrada com estes filtros.</div>';$('#news-count').textContent=rows.length+' '+t('found');$('#more-news').hidden=shown.length>=rows.length}
function isUrgent(n){const age=Date.now()-(Date.parse(n.date)||0),words=/\b(urgente|última hora|ao vivo|agora|oficial|confirmad[oa]|escalação|desfalque|lesão|gol|expuls|demit|contrata)\b/i;return age>=-1800000&&age<=21600000&&words.test(n.title||'')}
function renderSpotlight(){const lead=state.news.find(n=>n.image)||state.news[0],second=state.news.find(n=>n!==lead);if(!lead)return;$('#hero-news').innerHTML='<a href="'+esc(newsPath(lead))+'">'+media(lead,true)+'<div class="hero-copy"><span class="label">'+say('DESTAQUE','FEATURED','DESTACADO')+' · '+esc(lead.source)+'</span><h2>'+esc(lead.title)+'</h2><small>'+esc(formatDate(lead.date))+' · '+say('Ver página da notícia →','Open story page →','Ver página de la noticia →')+'</small></div></a>';const urgent=state.news.filter(isUrgent).slice(0,5),wire=$('.news-wire');wire.hidden=!urgent.length;if(urgent.length){const headlines=urgent.map(n=>'<a href="'+esc(newsPath(n))+'"><i class="urgent-dot"></i><span>'+esc(n.source)+'</span>'+esc(n.title)+'</a>').join('');$('#ticker').innerHTML='<div class="ticker-group">'+headlines+'</div><div class="ticker-group" aria-hidden="true" inert>'+headlines+'</div>';wire.classList.remove('paused')}else $('#ticker').innerHTML='';if(second)$('#mini-news').innerHTML='<a href="'+esc(newsPath(second))+'"><span>'+esc(second.source)+' · '+esc(formatDate(second.date))+'</span><h3>'+esc(second.title)+'</h3></a>'}
async function loadNews(manual=false){try{const response=await fetch('/api/news',{cache:'no-store'}),data=await response.json();if(!response.ok)throw new Error(data.error||'Fonte indisponível');const previous=state.news[0]?.link;state.news=(data.items||[]).sort((a,b)=>(Date.parse(b.date)||0)-(Date.parse(a.date)||0));const sources=[...new Set(state.news.map(n=>n.source))];$('#source').innerHTML='<option value="">'+t('sources')+'</option>'+sources.map(s=>'<option>'+esc(s)+'</option>').join('');$('#updated').textContent=(data.stale?t('cached')+' · ':t('latest')+' · ')+formatDate(data.updatedAt);$('#sources-health').textContent=(data.sources||[]).map(s=>s.name+': '+(s.available?t('available'):t('unavailable'))).join(' · ');renderNews();renderSpotlight();renderAlerts();const fresh=state.news.filter(n=>!state.seen.has(n.link)&&isUrgent(n));if(previous&&state.news[0]?.link!==previous&&fresh.length)announce(fresh[0]);if(manual)toast('Notícias atualizadas.');}catch(e){$('#updated').textContent='Atualização temporariamente indisponível';if(!state.news.length)$('#feed').innerHTML='<div class="empty">Não foi possível consultar as fontes agora. Tente novamente.</div>'}}
['#query','#source','#sort'].forEach(id=>$(id).addEventListener(id==='#query'?'input':'change',()=>{state.shownNews=6;renderNews()}));$('#more-news').onclick=()=>{state.shownNews+=6;renderNews()};$('#reload').onclick=()=>loadNews(true);
function renderAlerts(){const rows=state.news.slice(0,6);$('#alerts-list').innerHTML=rows.map(n=>'<a target="_blank" rel="noopener" href="'+esc(n.link)+'">'+esc(n.title)+'<small>'+esc(n.source)+' · '+esc(formatDate(n.date))+'</small></a>').join('');const unseen=state.news.filter(n=>!state.seen.has(n.link)).length,count=$('#alert-count');count.textContent=unseen>29?'29+':unseen;count.hidden=!unseen;$('#alerts-open').setAttribute('aria-label',unseen?say('Abrir central de notificações · '+unseen+' novas','Open notifications · '+unseen+' new','Abrir notificaciones · '+unseen+' nuevas'):say('Abrir central de notificações','Open notifications','Abrir notificaciones'))}
function openAlerts(){state.news.forEach(n=>state.seen.add(n.link));localStorage.setItem('nrn-seen',JSON.stringify([...state.seen].slice(-100)));$('#alert-count').hidden=true;setDialog('#alerts')}
$('#alerts-open').onclick=openAlerts;$('#alerts-rail').onclick=openAlerts;$('#enable-alerts').onclick=async()=>{if(!('Notification'in window)){toast('Este navegador não oferece notificações.');return}const result=await Notification.requestPermission();$('#permission').textContent=result==='granted'?'Avisos ativados neste aparelho.':'Permissão não concedida.';if(result==='granted')toast('Avisos rubro-negros ativados.')};
function announce(n){if('Notification'in window&&Notification.permission==='granted')new Notification('Nova no radar rubro-negro',{body:n.title,icon:'https://a.espncdn.com/i/teamlogos/soccer/500/819.png',tag:n.link});}
function initials(name){return name.split(/\s+/).slice(0,2).map(x=>x[0]).join('')}
function playerPhoto(p,className=''){return p.photo?'<img class="player-photo '+esc(className)+'" loading="lazy" decoding="async" src="'+esc(p.photo)+'" alt="'+esc(p.name)+'" data-initials="'+esc(initials(p.name))+'">':'<span class="initials">'+esc(initials(p.name))+'</span>'}
function playerCard(p){const selected=state.selected===p.id;return '<article class="player'+(selected?' selected':'')+'"><button class="player-choice" data-player="'+esc(p.id)+'"><div class="portrait">'+playerPhoto(p)+'<span class="jersey">#'+esc(p.number)+'</span>'+(selected?'<span class="checked">✓</span>':'')+'</div><div class="player-name"><strong>'+esc(p.name)+'</strong><small>'+esc(p.role||p.position)+'</small></div></button><button class="profile-button" data-profile="'+esc(p.id)+'">Ver detalhes ↗</button></article>'}
function visiblePlayers(){const q=fold($('#player-query').value),pos=$('#position').value;let rows=state.players.filter(p=>(!q||fold(p.name).includes(q))&&(!pos||p.position===pos));if(state.poll.startsWith('saida'))rows=[{id:'ninguem',name:'Ninguém agora',number:'—',position:'Manter o elenco',photo:'',country:'',age:null},...rows];return rows}
function renderPlayers(){const rows=visiblePlayers(),shown=rows.slice(0,state.shownPlayers);$('#players').innerHTML=shown.length?shown.map(playerCard).join(''):'<div class="empty">Nenhum jogador encontrado.</div>';$('#more-players').hidden=shown.length>=rows.length;$$('[data-player]').forEach(b=>b.onclick=()=>{state.selected=b.dataset.player;const p=state.players.find(x=>x.id===state.selected)||{name:'Ninguém agora'};$('#selection').textContent='Seu voto: '+p.name;$('#vote').disabled=false;renderPlayers()});$$('[data-profile]').forEach(b=>b.onclick=()=>showPlayer(b.dataset.profile))}
function showPlayer(id){const p=state.players.find(x=>x.id===id);if(!p)return;$('#details-content').innerHTML=playerPhoto(p,'detail-photo')+'<span class="eyebrow">ELENCO PROFISSIONAL</span><h2>'+esc(p.name)+'</h2><dl><dt>Camisa</dt><dd>#'+esc(p.number)+'</dd><dt>Posição</dt><dd>'+esc(p.role||p.position)+'</dd>'+(p.age?'<dt>Idade</dt><dd>'+p.age+' anos</dd>':'')+(p.country?'<dt>Nacionalidade</dt><dd>'+esc(p.country)+'</dd>':'')+'</dl>'+(p.profile?'<a class="external" target="_blank" rel="noopener" href="'+esc(p.profile)+'">Ver no elenco oficial do Flamengo ↗</a>':'')+(p.photoSource?'<a class="external" target="_blank" rel="noopener" href="'+esc(p.photoSource)+'">Fonte da fotografia ↗</a>':'');setDialog('#details')}
async function loadPlayers(){try{const r=await fetch('/api/players'),data=await r.json();if(!r.ok)throw new Error();state.players=data.players||[];$('#roster-date').textContent=(data.stale?'Última lista oficial disponível':'Elenco oficial atualizado')+' · '+formatDate(data.updatedAt);renderPlayers();renderResults();if(state.matches.length)renderRatings()}catch{$('#players').innerHTML='<div class="empty">Elenco indisponível. Tente novamente.</div>'}}
$('#player-query').oninput=()=>{state.shownPlayers=6;renderPlayers()};$('#position').onchange=()=>{state.shownPlayers=6;renderPlayers()};$('#more-players').onclick=()=>{state.shownPlayers+=6;renderPlayers()};
function activePoll(){return state.polls.find(p=>p.id===state.poll)||{total:0,options:[],mine:null}}
function renderResults(){
 const p=activePoll();$('#total').textContent=p.total??0;
 const ranked=[...(p.options||[])].sort((a,b)=>Number(b.votes)-Number(a.votes)).slice(0,7),previous=state.pollRanks[state.poll]||{};
 $('#results').innerHTML=ranked.length?ranked.map((x,index)=>{const rank=index+1,player=state.players.find(p=>p.id===x.player)||{name:x.player==='ninguem'?say('Ninguém agora','No one for now','Nadie por ahora'):say('Jogador','Player','Jugador'),photo:''},pct=p.total?Math.round(Number(x.votes)/Number(p.total)*100):0,moved=previous[x.player]&&previous[x.player]>rank;return '<div class="result'+(moved?' rank-up':'')+'" data-rank="'+rank+'" style="animation-delay:'+index*55+'ms"><div class="result-title">'+(player.photo?playerPhoto(player,'result-photo'):'<span class="result-avatar">'+esc(initials(player.name))+'</span>')+'<span>'+esc(player.name)+'</span><b>'+pct+'%</b></div><div class="track"><span style="width:'+pct+'%"></span></div></div>'}).join(''):'<p class="small">'+say('A disputa começa em zero. Dê o primeiro voto.','The ranking starts at zero. Cast the first vote.','El ranking empieza en cero. Envía el primer voto.')+'</p>';
 state.pollRanks[state.poll]=Object.fromEntries(ranked.map((x,index)=>[x.player,index+1]));
 const main=state.polls.find(row=>row.id.startsWith('melhor'))||{total:0,options:[]},first=[...(main.options||[])].sort((a,b)=>Number(b.votes)-Number(a.votes))[0],leader=$('#poll-leader');
 if(leader){if(first){const player=state.players.find(row=>row.id===first.player)||{name:say('Craque da torcida','Supporters’ player','Figura de la hinchada'),photo:''},pct=main.total?Math.round(Number(first.votes)/main.total*100):0;leader.innerHTML=(player.photo?playerPhoto(player,'leader-photo'):'<span class="leader-avatar">'+esc(initials(player.name))+'</span>')+'<span>'+say('LÍDER AGORA','CURRENT LEADER','LÍDER AHORA')+'</span><strong>'+esc(player.name)+'</strong><b>'+pct+say('% dos votos','% of votes','% de los votos')+'</b>'}else leader.innerHTML='<span>'+say('A VOTAÇÃO ESTÁ ABERTA','VOTING IS OPEN','LA VOTACIÓN ESTÁ ABIERTA')+'</span><strong>'+say('QUEM VAI LIDERAR?','WHO WILL LEAD?','¿QUIÉN LIDERARÁ?')+'</strong><b>'+say('Seja o primeiro a escolher','Be the first to choose','Sé el primero en elegir')+'</b>'}
 if(p.mine){const mine=state.players.find(x=>x.id===p.mine)||{name:p.mine==='ninguem'?say('Ninguém agora','No one for now','Nadie por ahora'):p.mine};$('#vote-status').textContent=say('Seu voto registrado: ','Your vote: ','Tu voto: ')+mine.name;$('#vote').disabled=true}
}
async function loadPolls(){try{const r=await fetch('/api/polls'),data=await r.json();if(!r.ok)throw new Error(data.error);state.polls=data.polls||[];renderResults()}catch(e){$('#results').innerHTML='<p class="small">'+esc(e.message||'Resultados indisponíveis.')+'</p>'}}
$$('.poll-tabs button').forEach(b=>b.onclick=()=>{state.poll=b.dataset.poll;state.selected=null;state.shownPlayers=6;$$('.poll-tabs button').forEach(x=>x.setAttribute('aria-selected',x===b));$('#poll-question').textContent=state.poll.startsWith('melhor')?say('Quem merece o troféu da torcida?','Who deserves the supporters’ trophy?','¿Quién merece el trofeo de la hinchada?'):say('Quem deveria sair?','Who should leave?','¿Quién debería salir?');$('#selection').textContent=say('Toque em um jogador e confirme.','Tap a player and confirm.','Toca a un jugador y confirma.');$('#vote-status').textContent='';$('#vote').disabled=true;renderPlayers();renderResults()});
$('#vote').onclick=async()=>{if(!state.selected)return;$('#vote').disabled=true;try{const r=await fetch('/api/vote',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({poll:state.poll,player:state.selected})}),data=await r.json();if(!r.ok)throw new Error(data.error);toast(data.message);await loadPolls()}catch(e){toast(e.message||'Não foi possível votar.');$('#vote').disabled=false}};$('#refresh-polls').onclick=loadPolls;
function renderGroups(){const rows=state.groups;$('#groups-list').innerHTML=rows.length?rows.map(g=>'<article class="group-card"><span class="group-type">'+esc(g.category)+' · '+esc(g.region)+'</span><h3>'+esc(g.name)+'</h3><p>'+esc(g.description)+'</p><a target="_blank" rel="noopener" href="'+esc(g.url)+'">'+say('Entrar no WhatsApp ↗','Join on WhatsApp ↗','Entrar en WhatsApp ↗')+'</a></article>').join(''):'<div class="empty">'+say('Ainda não há grupos aprovados nesta seleção. Cadastre o primeiro.','No approved groups match this search yet. Add the first one.','Todavía no hay grupos aprobados en esta selección. Registra el primero.')+'</div>';const more=$('#more-groups');if(more){more.hidden=!state.groupsMore;more.textContent=t('moreGroups')}}
async function loadGroups(reset=true){try{const q=$('#group-query').value.trim(),cat=$('#group-category').value,params=new URLSearchParams({limit:'24'});if(q)params.set('q',q);if(cat)params.set('category',cat);if(!reset&&state.groupsCursor)params.set('cursor',state.groupsCursor);const r=await fetch('/api/groups?'+params,{cache:'no-store'}),data=await r.json();if(!r.ok)throw new Error();state.groups=reset?(data.groups||[]):[...state.groups,...(data.groups||[])];state.groupsCursor=data.nextCursor||null;state.groupsMore=!!data.nextCursor;renderGroups()}catch{$('#groups-list').innerHTML='<div class="empty">Diretório temporariamente indisponível.</div>'}}
let groupSearchTimer;$('#group-query').oninput=()=>{clearTimeout(groupSearchTimer);groupSearchTimer=setTimeout(()=>loadGroups(true),280)};$('#group-category').onchange=()=>loadGroups(true);if($('#more-groups'))$('#more-groups').onclick=()=>loadGroups(false);$('#group-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,button=form.querySelector('button'),payload=Object.fromEntries(new FormData(form));button.disabled=true;try{const r=await fetch('/api/groups',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}),data=await r.json();if(!r.ok)throw new Error(data.error);$('#group-status').textContent=data.message;form.reset();toast('Grupo enviado para análise.')}catch(err){$('#group-status').textContent=err.message||'Não foi possível enviar agora.'}finally{button.disabled=false}};
function brDay(date){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(date))}
function matchDate(date){const now=new Date(),target=new Date(date),a=brDay(now).split('-').map(Number),b=brDay(target).split('-').map(Number),diff=Math.round((Date.UTC(b[0],b[1]-1,b[2])-Date.UTC(a[0],a[1]-1,a[2]))/86400000),time=new Intl.DateTimeFormat(intlLocale,{timeZone:'America/Sao_Paulo',hour:'2-digit',minute:'2-digit'}).format(target);if(diff===0)return t('today')+' · '+time;if(diff===1)return t('tomorrow')+' · '+time;if(diff>1&&diff<=6)return new Intl.DateTimeFormat(intlLocale,{timeZone:'America/Sao_Paulo',weekday:'long'}).format(target).toUpperCase()+' · '+time;return new Intl.DateTimeFormat(intlLocale,{timeZone:'America/Sao_Paulo',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(target)}
function teamMark(team,size=''){return team.logo?'<img class="team-logo '+size+'" src="'+esc(team.logo)+'" alt="">':'<span class="team-monogram '+size+'">'+esc(team.short||team.name.slice(0,3).toUpperCase())+'</span>'}
function headlineMatch(){const live=state.matches.find(match=>match.state==='in');if(live)return live;const future=state.matches.filter(match=>match.state!=='post'&&Date.parse(match.date)>=Date.now()-7200000).sort((a,b)=>Date.parse(a.date)-Date.parse(b.date))[0];if(future)return future;return [...state.matches].filter(match=>match.state==='post').sort((a,b)=>Date.parse(b.date)-Date.parse(a.date))[0]}
function focusMatchDetails(id,event){event?.preventDefault();state.focusedMatch=id;renderMatchStudio();history.replaceState(null,'','#lineup');setTimeout(()=>{const target=$('#lineup'),top=target.getBoundingClientRect().top+scrollY-82;scrollTo({top,behavior:'instant'})})}
function renderMobileMatch(match){const mobile=$('#mobile-match');if(!mobile)return;if(!match){mobile.className='mobile-match is-empty';mobile.innerHTML='<a href="#jogos"><strong>'+say('AGENDA EM ATUALIZAÇÃO','FIXTURES UPDATING','CALENDARIO ACTUALIZÁNDOSE')+'</strong><span>'+say('Abra a central para tentar novamente.','Open the match centre to try again.','Abre la central para intentarlo de nuevo.')+'</span></a>';return}const playing=match.state==='in',finished=match.state==='post',label=playing?t('live'):finished?t('lastGame'):t('next'),score=playing||finished,center=score?'<div class="mobile-score"><b>'+esc(match.home.score||'0')+'</b><span>×</span><b>'+esc(match.away.score||'0')+'</b></div>':'<div class="mobile-kickoff"><b>×</b><time datetime="'+esc(match.date)+'">'+esc(matchDate(match.date))+'</time></div>';mobile.className='mobile-match '+(playing?'is-live':finished?'is-finished':'is-next');mobile.innerHTML='<a href="#jogos"><div class="mobile-match-meta"><span>'+(playing?'<i></i>':'')+label+'</span><b>'+esc(match.competition||say('Flamengo em campo','Flamengo match','Partido de Flamengo'))+'</b></div><div class="mobile-match-teams"><div>'+teamMark(match.home,'mobile-logo')+'<strong>'+esc(match.home.name)+'</strong></div>'+center+'<div>'+teamMark(match.away,'mobile-logo')+'<strong>'+esc(match.away.name)+'</strong></div></div>'+(score?'<time class="mobile-match-date" datetime="'+esc(match.date)+'">'+esc(matchDate(match.date))+'</time>':'')+'<small><b>'+t('where')+':</b> '+esc(match.venue||say('A confirmar','To be confirmed','Por confirmar'))+' <em>'+t('details')+'</em></small></a>'}
function updateCountdown(){const el=$('#match-countdown');if(!el)return;const kickoff=Date.parse(el.dataset.kickoff),left=kickoff-Date.now();if(!Number.isFinite(left)){el.innerHTML='<strong>'+say('HORÁRIO EM CONFIRMAÇÃO','KICKOFF TO BE CONFIRMED','HORARIO POR CONFIRMAR')+'</strong>';return}if(left<=0){el.innerHTML='<strong>'+say('O JOGO VAI COMEÇAR','KICKOFF IS NEAR','EL PARTIDO VA A COMENZAR')+'</strong><span>'+say('Atualizando o placar…','Updating the score…','Actualizando el marcador…')+'</span>';if(Date.now()-state.lastKickoffRefresh>30000){state.lastKickoffRefresh=Date.now();loadMatches()}return}const seconds=Math.floor(left/1000),days=Math.floor(seconds/86400),hours=Math.floor(seconds%86400/3600),minutes=Math.floor(seconds%3600/60),secs=seconds%60;el.innerHTML=[[t('days'),days],[t('hours'),hours],[t('minutes'),minutes],[t('seconds'),secs]].map(([label,value])=>'<div><b>'+String(value).padStart(2,'0')+'</b><span>'+label+'</span></div>').join('')}
function renderLiveboard(){const board=$('#match-liveboard'),match=headlineMatch();renderMobileMatch(match);if(!board)return;if(!match){board.innerHTML='<div class="liveboard-loading">'+say('O próximo jogo ainda não entrou no calendário.','The next match is not on the calendar yet.','El próximo partido aún no aparece en el calendario.')+'</div>';return}const playing=match.state==='in',finished=match.state==='post',label=playing?t('live'):finished?t('lastGame'):t('next'),clock=playing?t('live')+' · '+(match.status||t('live')):say('FIM DE JOGO','FULL TIME','FINAL'),center=finished||playing?'<div class="live-score"><b>'+esc(match.home.score||'0')+'</b><span>×</span><b>'+esc(match.away.score||'0')+'</b><small>'+esc(clock)+'</small></div>':'<div id="match-countdown" class="match-countdown" data-kickoff="'+esc(match.date)+'"></div>';board.className='match-liveboard '+(playing?'is-live':finished?'is-finished':'is-next');board.innerHTML='<div class="liveboard-top"><span class="live-label">'+(playing?'<i></i>':'')+label+'</span><b>'+esc(match.competition||say('Jogo do Flamengo','Flamengo match','Partido de Flamengo'))+'</b></div><div class="liveboard-main"><div class="live-team">'+teamMark(match.home,'large')+'<strong>'+esc(match.home.name)+'</strong></div><div class="liveboard-center">'+center+'<time datetime="'+esc(match.date)+'">'+esc(matchDate(match.date))+'</time></div><div class="live-team">'+teamMark(match.away,'large')+'<strong>'+esc(match.away.name)+'</strong></div></div><div class="liveboard-foot"><span><b>'+t('where')+':</b> '+esc(match.venue||say('Local ainda não divulgado','Venue not announced yet','Lugar aún no anunciado'))+'</span><a href="#lineup" data-focus-match="'+esc(match.id)+'">'+t('lineup')+'</a></div>';const focus=board.querySelector('[data-focus-match]');if(focus)focus.onclick=event=>focusMatchDetails(match.id,event);updateCountdown()}
const eventNames={goal:['GOL','GOAL','GOL'],shot_off:['CHUTE PARA FORA','SHOT WIDE','REMATE FUERA'],shot_on:['CHUTE NO GOL','SHOT ON TARGET','REMATE AL ARCO'],shot_blocked:['CHUTE BLOQUEADO','SHOT BLOCKED','REMATE BLOQUEADO'],shot:['FINALIZAÇÃO','SHOT','REMATE'],corner:['ESCANTEIO','CORNER','CÓRNER'],goal_kick:['TIRO DE META','GOAL KICK','SAQUE DE META'],foul:['FALTA','FOUL','FALTA'],yellow_card:['CARTÃO AMARELO','YELLOW CARD','TARJETA AMARILLA'],red_card:['CARTÃO VERMELHO','RED CARD','TARJETA ROJA'],substitution:['SUBSTITUIÇÃO','SUBSTITUTION','CAMBIO'],offside:['IMPEDIMENTO','OFFSIDE','FUERA DE JUEGO'],halftime:['INTERVALO','HALF-TIME','DESCANSO'],fulltime:['FIM DE JOGO','FULL-TIME','FINAL'],kickoff:['BOLA ROLANDO','KICK-OFF','RUEDA EL BALÓN'],update:['LANCE ATUALIZADO','MATCH UPDATE','JUGADA ACTUALIZADA']};
function eventName(type){const row=eventNames[type]||eventNames.update;return row[locale==='en'?1:locale==='es'?2:0]}
function isFlamengo(team){return String(team?.id)==='819'||fold(team?.name).includes('flamengo')}
function eventPoint(match,event){if(event?.coordinate)return event.coordinate;const home=String(event?.teamId)===String(match.home.id),attacking=home?78:22,type=event?.type;let x=attacking;if(type==='goal')x=home?94:6;if(type==='corner')x=home?96:4;if(type==='goal_kick')x=home?15:85;const seed=[...String(event?.id||event?.clock||'fla')].reduce((sum,char)=>sum+char.charCodeAt(0),0);return {x,y:24+(seed%53)}}
function renderMatchPulse(){
 const pulse=$('#match-pulse');if(!pulse)return;const match=state.matches.find(row=>row.state==='in');
 const marker=$('#event-marker'),call=$('#event-call'),list=$('#match-events'),source=$('#pulse-source');
 if(!match){pulse.className='match-pulse is-waiting';marker.hidden=true;call.innerHTML='<small>'+say('ENTRA NO AR COM A BOLA ROLANDO','LIVE WHEN THE MATCH STARTS','EN VIVO CUANDO EMPIECE')+'</small><strong>'+say('Placar e lances em atualização automática','Automatic score and match events','Marcador y jugadas automáticas')+'</strong><span>'+say('Finalização, escanteio, falta, cartão, substituição e gol.','Shots, corners, fouls, cards, substitutions and goals.','Remates, córners, faltas, tarjetas, cambios y goles.')+'</span>';list.innerHTML='<li><time>—</time><span><b>'+say('CENTRAL PRONTA','CENTRE READY','CENTRAL LISTA')+'</b> '+say('O acompanhamento aparece aqui quando o jogo começar.','Coverage appears here when the match starts.','El seguimiento aparece aquí cuando empiece el partido.')+'</span></li>';source.textContent=say('Fonte esportiva identificada · pode haver pequeno atraso','Identified sports source · a short delay is possible','Fuente deportiva identificada · puede haber un pequeño retraso');return;
 }
 const events=Array.isArray(match.events)?match.events:[],latest=events[0];pulse.className='match-pulse is-live';marker.hidden=!latest;
 if(latest){const point=eventPoint(match,latest),team=String(latest.teamId)===String(match.home.id)?match.home:String(latest.teamId)===String(match.away.id)?match.away:null,forFla=isFlamengo(team);marker.className='event-marker type-'+esc(latest.type)+(forFla?' for-flamengo':'');marker.style.left=point.x+'%';marker.style.top=point.y+'%';call.innerHTML='<small>'+esc(latest.clock)+' · '+esc(team?.name||say('PARTIDA','MATCH','PARTIDO'))+'</small><strong>'+esc(eventName(latest.type))+'</strong><span>'+esc(forFla?say('Lance do Mengão','Flamengo move','Jugada de Flamengo'):team?.name||match.status)+'</span>'}else call.innerHTML='<small>'+esc(match.status||t('live'))+'</small><strong>'+say('BOLA ROLANDO','MATCH IN PLAY','PARTIDO EN JUEGO')+'</strong><span>'+say('Aguardando o próximo lance da fonte.','Waiting for the next event from the source.','Esperando la próxima jugada de la fuente.')+'</span>';
 list.innerHTML=events.length?events.slice(0,7).map(event=>{const team=String(event.teamId)===String(match.home.id)?match.home:String(event.teamId)===String(match.away.id)?match.away:null;return '<li class="event-'+esc(event.type)+'"><time>'+esc(event.clock)+'</time><span><b>'+esc(eventName(event.type))+'</b> '+esc(team?.name||'')+'</span></li>'}).join(''):'<li><time>'+esc(match.status||'—')+'</time><span><b>'+say('AO VIVO','LIVE','EN VIVO')+'</b> '+say('Placar ativo; aguardando o primeiro lance detalhado.','Score active; waiting for the first detailed event.','Marcador activo; esperando la primera jugada detallada.')+'</span></li>';
 source.textContent=say('ESPN · atualização automática a cada 15 segundos · representação visual do evento','ESPN · automatic refresh every 15 seconds · visual event representation','ESPN · actualización automática cada 15 segundos · representación visual del evento');
}
let audioContext;
async function playGoalSound(){
 if(!state.goalSound)return;const AudioEngine=window.AudioContext||window.webkitAudioContext;if(!AudioEngine)return;audioContext=audioContext||new AudioEngine();await audioContext.resume();const now=audioContext.currentTime,master=audioContext.createGain();master.gain.setValueAtTime(.0001,now);master.gain.exponentialRampToValueAtTime(.075,now+.035);master.gain.exponentialRampToValueAtTime(.0001,now+1.45);master.connect(audioContext.destination);[392,523.25,659.25,783.99].forEach((frequency,index)=>{const oscillator=audioContext.createOscillator(),gain=audioContext.createGain(),start=now+index*.16;oscillator.type=index<2?'triangle':'sine';oscillator.frequency.setValueAtTime(frequency,start);gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(.6,start+.025);gain.gain.exponentialRampToValueAtTime(.0001,start+.42);oscillator.connect(gain).connect(master);oscillator.start(start);oscillator.stop(start+.46)});
}
function syncGoalSound(){const button=$('#goal-sound');if(!button)return;button.setAttribute('aria-pressed',String(state.goalSound));button.innerHTML='<span aria-hidden="true">'+(state.goalSound?'♫':'♪')+'</span><b>'+say(state.goalSound?'SOM DE GOL ATIVO':'ATIVAR SOM DE GOL',state.goalSound?'GOAL SOUND ON':'ENABLE GOAL SOUND',state.goalSound?'SONIDO DE GOL ACTIVO':'ACTIVAR SONIDO DE GOL')+'</b>'}
function showGoal(match){const flash=$('#goal-flash');if(!flash)return;const score=match.home.name+' '+match.home.score+' × '+match.away.score+' '+match.away.name;$('#goal-flash-score').textContent=score;flash.hidden=false;clearTimeout(showGoal.timer);showGoal.timer=setTimeout(()=>flash.hidden=true,4200);playGoalSound().catch(()=>{});if('Notification'in window&&Notification.permission==='granted')new Notification(say('GOOOL DO FLAMENGO!','FLAMENGO GOAL!','¡GOL DE FLAMENGO!'),{body:score,icon:'https://a.espncdn.com/i/teamlogos/soccer/500/819.png',tag:'goal-'+match.id+'-'+match.home.score+'-'+match.away.score})}
function detectFlamengoGoal(previous,next){if(!previous.length)return;for(const match of next){const old=previous.find(row=>row.id===match.id||row.providerEventId&&row.providerEventId===match.providerEventId);if(!old||!(old.state==='in'||match.state==='in'))continue;const flaHome=isFlamengo(match.home),oldScore=Number(flaHome?old.home.score:old.away.score),newScore=Number(flaHome?match.home.score:match.away.score);if(Number.isFinite(oldScore)&&Number.isFinite(newScore)&&newScore>oldScore)showGoal(match)}}
function predictionFor(id){return state.matchOpinions.predictions?.find(row=>row.match===id)||{total:0,options:[],mine:null,mineHome:null,mineAway:null}}
function ratingFor(match,player){return state.matchOpinions.ratings?.find(row=>row.match===match&&row.player===player)||{average:null,ratings:0,mine:null}}
function matchChoice(m,key){return key==='draw'?say('Empate','Draw','Empate'):key==='home'?m.home.name:m.away.name}
function actualChoice(m){if(m.state!=='post')return null;const h=Number(m.home.score),a=Number(m.away.score);if(!Number.isFinite(h)||!Number.isFinite(a))return null;return h===a?'draw':h>a?'home':'away'}
function renderPrediction(m){
 if(!m)return;
 const poll=predictionFor(m.id),winner=actualChoice(m),counts=(poll.options||[]).reduce((all,row)=>(all[row.choice]=(all[row.choice]||0)+Number(row.votes),all),{}),order={home:0,draw:1,away:2};
 const outcomes=['home','draw','away'].map(key=>({key,label:matchChoice(m,key),votes:counts[key]||0,pct:poll.total?Math.round((counts[key]||0)/poll.total*100):0})).sort((a,b)=>b.votes-a.votes||order[a.key]-order[b.key]);
 const scores=(poll.options||[]).filter(row=>Number.isInteger(Number(row.homeScore))&&Number.isInteger(Number(row.awayScore))).map(row=>({key:Number(row.homeScore)+'-'+Number(row.awayScore),home:Number(row.homeScore),away:Number(row.awayScore),votes:Number(row.votes),pct:poll.total?Math.round(Number(row.votes)/poll.total*100):0})).sort((a,b)=>b.votes-a.votes||a.home-b.home||a.away-b.away);
 const previous=state.predictionRanks[m.id]||{},leader=scores[0],stored=state.scoreDrafts[m.id];if(!stored)state.scoreDrafts[m.id]={home:poll.mineHome??0,away:poll.mineAway??0,touched:false};else if(!stored.touched&&poll.mineHome!==null){stored.home=Number(poll.mineHome);stored.away=Number(poll.mineAway)}const draft=state.scoreDrafts[m.id];
 $('#prediction-game').textContent=m.home.name+' × '+m.away.name;
 const leaderEl=$('#prediction-leader');
 if(leaderEl)leaderEl.innerHTML=leader?'<div class="prediction-leader-mark"><span class="score-mark">'+leader.home+'×'+leader.away+'</span></div><div><small>'+say('PLACAR MAIS VOTADO','MOST POPULAR SCORE','MARCADOR MÁS VOTADO')+'</small><strong>'+esc(m.home.short||m.home.name)+' '+leader.home+' × '+leader.away+' '+esc(m.away.short||m.away.name)+'</strong><span>'+leader.pct+'% · '+leader.votes+' '+say(leader.votes===1?'palpite':'palpites',leader.votes===1?'prediction':'predictions',leader.votes===1?'pronóstico':'pronósticos')+'</span></div>':'<div class="prediction-leader-mark is-empty">?</div><div><small>'+say('RANKING AO VIVO','LIVE RANKING','RANKING EN VIVO')+'</small><strong>'+say('A disputa começa aqui','The contest starts here','La disputa empieza aquí')+'</strong><span>'+say('Monte o placar em poucos toques.','Set the score in a few taps.','Arma el marcador en pocos toques.')+'</span></div>';
 const official=m.probabilities;
 $('#official-probabilities').innerHTML=official?'<details class="official-probs"><summary>'+say('Ver probabilidades da fonte','See source probabilities','Ver probabilidades de la fuente')+' · '+esc(official.source)+'</summary>'+['home','draw','away'].map(k=>'<div class="prob-row"><span>'+esc(matchChoice(m,k))+'</span><b>'+official[k]+'%</b><div class="prob-track"><i style="width:'+official[k]+'%"></i></div></div>').join('')+'</details>':'';
 $('#prediction-options').className='prediction-options';
 const open=m.state==='pre'&&Date.now()<Date.parse(m.date),scorePicker='<div class="score-picker"><div class="score-team">'+teamMark(m.home,'score-logo')+'<strong>'+esc(m.home.short||m.home.name)+'</strong><div class="score-stepper"><button data-score-side="home" data-score-delta="-1" '+(!open||draft.home===0?'disabled':'')+' aria-label="'+say('Diminuir gols do mandante','Decrease home score','Restar goles del local')+'">−</button><output>'+draft.home+'</output><button data-score-side="home" data-score-delta="1" '+(!open||draft.home===15?'disabled':'')+' aria-label="'+say('Aumentar gols do mandante','Increase home score','Sumar goles del local')+'">+</button></div></div><span class="score-x">×</span><div class="score-team">'+teamMark(m.away,'score-logo')+'<strong>'+esc(m.away.short||m.away.name)+'</strong><div class="score-stepper"><button data-score-side="away" data-score-delta="-1" '+(!open||draft.away===0?'disabled':'')+' aria-label="'+say('Diminuir gols do visitante','Decrease away score','Restar goles del visitante')+'">−</button><output>'+draft.away+'</output><button data-score-side="away" data-score-delta="1" '+(!open||draft.away===15?'disabled':'')+' aria-label="'+say('Aumentar gols do visitante','Increase away score','Sumar goles del visitante')+'">+</button></div></div><button id="save-score" class="save-score" '+(!open?'disabled':'')+'>'+say(poll.mineHome!==null?'ATUALIZAR MEU PLACAR':'CONFIRMAR '+draft.home+' × '+draft.away,poll.mineHome!==null?'UPDATE MY SCORE':'CONFIRM '+draft.home+' × '+draft.away,poll.mineHome!==null?'ACTUALIZAR MI MARCADOR':'CONFIRMAR '+draft.home+' × '+draft.away)+'</button></div>';
 const exactRanking='<div class="score-ranking"><div class="score-ranking-head"><strong>'+say('PLACARES MAIS VOTADOS','TOP SCORE PICKS','MARCADORES MÁS VOTADOS')+'</strong><span>'+poll.total+' '+say('na disputa','in the ranking','en el ranking')+'</span></div>'+(scores.length?'<ol>'+scores.slice(0,5).map((item,index)=>{const rank=index+1,moved=previous[item.key]&&previous[item.key]>rank;return '<li class="score-rank rank-'+rank+(moved?' rank-up':'')+'" style="--rank-delay:'+index*70+'ms"><span class="score-rank-number">'+rank+'</span><strong>'+item.home+' × '+item.away+'</strong><span>'+item.votes+' '+say(item.votes===1?'voto':'votos',item.votes===1?'vote':'votes',item.votes===1?'voto':'votos')+'</span><b>'+item.pct+'%</b>'+(moved?'<em>↑ '+say('subiu','up','subió')+'</em>':'')+'<i style="--score-rank-width:'+item.pct+'%"></i></li>'}).join('')+'</ol>':'<p>'+say('O primeiro placar pode ser o seu.','Your score can be the first.','Tu marcador puede ser el primero.')+'</p>')+'</div>';
 const outcomeStrip='<div class="outcome-strip">'+outcomes.map(item=>'<div><span>'+esc(item.label)+'</span><b>'+(poll.total?item.pct+'%':'—')+'</b></div>').join('')+'</div>';
 const result=m.state==='post'?'<div class="outcome"><strong>'+say('RESULTADO FINAL: ','FINAL SCORE: ','RESULTADO FINAL: ')+esc(m.home.score)+' × '+esc(m.away.score)+'</strong>'+(poll.mineHome!==null?'<span>'+ (Number(poll.mineHome)===Number(m.home.score)&&Number(poll.mineAway)===Number(m.away.score)?say('Você cravou o placar!','You nailed the score!','¡Acertaste el marcador!'):poll.mine===winner?say('Você acertou quem levaria.','You picked the right result.','Acertaste quién ganaría.'):say('Não foi dessa vez.','Not this time.','No fue esta vez.'))+'</span>':'')+'</div>':'';
 $('#prediction-options').innerHTML=scorePicker+exactRanking+outcomeStrip+result;
 state.predictionRanks[m.id]=Object.fromEntries(scores.map((item,index)=>[item.key,index+1]));
 $$('[data-score-side]').forEach(button=>button.onclick=()=>{const side=button.dataset.scoreSide,delta=Number(button.dataset.scoreDelta);draft[side]=Math.max(0,Math.min(15,draft[side]+delta));draft.touched=true;renderPrediction(m)});if($('#save-score'))$('#save-score').onclick=()=>savePrediction(m,draft.home,draft.away);
 $('#prediction-status').textContent=open?(poll.mineHome!==null?say('Seu palpite está salvo e pode ser alterado até o início.','Your pick is saved and can be changed before kickoff.','Tu pronóstico está guardado y puede cambiarse antes del inicio.'):say('Escolha os gols e confirme uma vez.','Set the goals and confirm once.','Elige los goles y confirma una vez.')):say('Palpites encerrados para esta partida.','Predictions are closed for this match.','Pronósticos cerrados para este partido.');
}
function renderLineup(m){if(!m)return;const groups=m.lineups||[],status=m.lineupStatus||(m.state==='post'?'historical':m.state==='in'?'confirmed':'unavailable');if(!groups.length){const title=m.state==='post'?say('FICHA SEM OS 11 INICIAIS','STARTING XI NOT AVAILABLE','ONCE INICIAL NO DISPONIBLE'):say('A ESCALAÇÃO AINDA NÃO SAIU','LINEUP NOT RELEASED YET','LA ALINEACIÓN AÚN NO FUE PUBLICADA'),copy=m.state==='post'?say('A fonte da partida não trouxe a lista completa deste jogo. Escolha outra data acima para consultar as escalações encontradas.','The match source did not provide the full team sheet. Choose another match above.','La fuente del partido no publicó la lista completa. Elige otro partido arriba.'):say('Quando a ficha esportiva publicar os jogadores, esta área será atualizada sozinha.','This area updates automatically when the match provider releases the players.','Esta área se actualizará automáticamente cuando la fuente publique los jugadores.');$('#lineup').innerHTML='<div class="lineup-board"><div class="lineup-empty"><div><strong>'+title+'</strong><p>'+copy+'</p></div></div></div>';return}const label=status==='probable'?say('PROVÁVEL DO FLAMENGO','PROBABLE FLAMENGO XI','PROBABLE DE FLAMENGO'):status==='historical'?say('TIME QUE ENTROU EM CAMPO','TEAM THAT STARTED','EQUIPO QUE FUE TITULAR'):say('ESCALAÇÃO CONFIRMADA','CONFIRMED LINEUP','ALINEACIÓN CONFIRMADA'),basis=m.lineupBasis?'<span>'+say('Base: ','Based on: ','Base: ')+esc(m.lineupBasis.game)+' · '+esc(matchDate(m.lineupBasis.date))+'</span>':'<span>'+say('Fonte: ','Source: ','Fuente: ')+esc(m.dataSource||'ESPN')+'</span>';$('#lineup').innerHTML='<div class="lineup-source '+esc(status)+'"><strong>'+label+'</strong>'+basis+'</div><div class="lineup-board '+(groups.length===1?'one-team':'')+'">'+groups.slice(0,2).map(group=>'<section class="lineup-team"><h4>'+esc(group.team)+(group.formation?' · '+esc(group.formation):'')+'</h4>'+(status==='probable'?'<small class="probable-note">'+say('Pode mudar até a bola rolar','May change before kickoff','Puede cambiar antes del inicio')+'</small>':'')+'<div class="lineup-xi">'+group.starters.map(p=>'<div class="lineup-player">'+(p.photo?'<img src="'+esc(p.photo)+'" alt="'+esc(p.name)+'">':'<span>'+esc(initials(p.name))+'</span>')+'<b title="'+esc(p.name)+'">'+esc(p.name.split(' ').slice(-1)[0])+'</b><small>'+esc(p.number||p.position)+'</small></div>').join('')+'</div></section>').join('')+'</div>'}
function ratingPlayers(m){const group=(m?.lineups||[]).find(x=>x.teamId==='819'||fold(x.team).includes('flamengo'));if(group?.starters.length)return group.starters.map(p=>{const official=state.players.find(x=>fold(x.name).includes(fold(p.name))||fold(p.name).includes(fold(x.name)));return {...p,id:official?.id||p.id,photo:official?.photo||p.photo}});return state.players}
function renderRatings(){const select=$('#rating-match'),m=state.matches.find(x=>x.id===(select.value||state.ratingMatch));if(!m||m.state!=='post'){$('#ratings-list').innerHTML='<div class="empty">'+say('As notas abrem depois do apito final.','Ratings open after full-time.','Las notas abren después del final.')+'</div>';return}state.ratingMatch=m.id;const players=ratingPlayers(m).slice(0,18);$('#ratings-list').className='ratings-list';$('#ratings-list').innerHTML='<p class="rating-hint">'+say('Avalie só quem quiser. A nota salva ao soltar o controle.','Rate only who you want. The score saves when you release the control.','Evalúa solo a quien quieras. La nota se guarda al soltar el control.')+'</p>'+players.map(p=>{const row=ratingFor(m.id,p.id),value=row.mine||Math.round(row.average)||7;return '<article class="rating-card">'+(p.photo?'<img src="'+esc(p.photo)+'" alt="'+esc(p.name)+'">':'<span class="rating-avatar">'+esc(initials(p.name))+'</span>')+'<div><strong>'+esc(p.name)+'</strong><small>'+(row.average?Number(row.average).toFixed(1)+' '+say('de média','average','de media')+' · '+row.ratings+' '+say('notas','ratings','notas'):say('Ainda sem média','No average yet','Aún sin media'))+'</small></div><label class="rating-score"><output>'+value+'</output><input type="range" min="1" max="10" value="'+value+'" data-rating="'+esc(p.id)+'" aria-label="'+say('Nota para ','Rating for ','Nota para ')+esc(p.name)+'"></label></article>'}).join('');$$('[data-rating]').forEach(input=>{input.oninput=()=>input.previousElementSibling.textContent=input.value;input.onchange=()=>saveRating(m,input.dataset.rating)})}
function renderMatchStudio(){const selected=state.matches.find(match=>match.id===state.focusedMatch),live=state.matches.find(match=>match.state==='in'),next=state.matches.find(match=>match.state!=='post'&&Date.parse(match.date)>=Date.now()-7200000),focus=selected||live||next||state.matches.at(-1);if(focus)state.focusedMatch=focus.id;$('#match-focus').innerHTML=state.matches.map(match=>{const kind=match.state==='post'?say('JÁ JOGOU','PLAYED','YA JUGÓ'):match.state==='in'?t('live'):say('VAI JOGAR','UPCOMING','PRÓXIMO');return '<option value="'+esc(match.id)+'" '+(match.id===state.focusedMatch?'selected':'')+'>'+esc(kind+' · '+matchDate(match.date)+' · '+match.home.name+' × '+match.away.name)+'</option>'}).join('');const finished=state.matches.filter(match=>match.state==='post').reverse();if(!state.ratingMatch&&finished[0])state.ratingMatch=finished[0].id;$('#rating-match').innerHTML=finished.length?finished.map(match=>'<option value="'+esc(match.id)+'" '+(match.id===state.ratingMatch?'selected':'')+'>'+esc(matchDate(match.date)+' · '+match.home.name+' × '+match.away.name)+'</option>').join(''):'<option value="">'+say('Nenhum jogo encerrado','No finished match','Ningún partido finalizado')+'</option>';renderLineup(focus);renderPrediction(focus);renderRatings()}
function renderMatches(){const now=Date.now(),completed=state.matches.filter(match=>match.state==='post').slice(-1),upcoming=state.matches.filter(match=>match.state!=='post'&&Date.parse(match.date)>=now-7200000).slice(0,4),rows=[...completed,...upcoming];renderLiveboard();renderMatchPulse();$('#matches').innerHTML=rows.length?rows.map(match=>{const scored=match.state==='post'||match.state==='in',label=match.state==='post'?t('lastGame'):match.state==='in'?t('live'):t('scheduled'),score=scored?'<div class="match-score"><b>'+esc(match.home.score||'—')+'</b><span>×</span><b>'+esc(match.away.score||'—')+'</b></div>':'<div class="match-time">'+new Intl.DateTimeFormat(intlLocale,{timeZone:'America/Sao_Paulo',hour:'2-digit',minute:'2-digit'}).format(new Date(match.date))+'</div>';return '<article class="match-card"><div class="match-meta"><span>'+label+'</span><b>'+esc(match.competition||match.status)+'</b></div><time datetime="'+esc(match.date)+'">'+esc(matchDate(match.date))+'</time><div class="match-teams"><div>'+teamMark(match.home)+'<strong>'+esc(match.home.name)+'</strong></div>'+score+'<div>'+teamMark(match.away)+'<strong>'+esc(match.away.name)+'</strong></div></div><small><b>'+t('where')+':</b> '+esc(match.venue||match.status||say('Local ainda não divulgado','Venue not announced yet','Lugar aún no anunciado'))+'</small></article>'}).join(''):'<div class="empty">'+say('Nenhum jogo apareceu no calendário agora.','No matches are listed right now.','No hay partidos en el calendario ahora.')+'</div>';renderMatchStudio()}
async function loadMatchOpinions(){try{const r=await fetch('/api/match-opinions',{cache:'no-store'}),data=await r.json();if(!r.ok)throw new Error(data.error);state.matchOpinions=data;state.opinionsLoaded=true;renderMatchStudio()}catch{$('#prediction-status').textContent=say('Os palpites estão temporariamente indisponíveis.','Predictions are temporarily unavailable.','Los pronósticos no están disponibles temporalmente.')}}
async function savePrediction(m,homeScore,awayScore){try{const r=await fetch('/api/match-prediction',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({match:m.id,homeScore,awayScore})}),data=await r.json();if(!r.ok)throw new Error(data.error);toast(data.message);await loadMatchOpinions()}catch(e){toast(e.message||say('Não foi possível salvar o palpite.','Could not save the prediction.','No se pudo guardar el pronóstico.'))}}
async function saveRating(m,player){const input=$('[data-rating="'+CSS.escape(player)+'"]');try{const r=await fetch('/api/player-rating',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({match:m.id,player,rating:Number(input.value)})}),data=await r.json();if(!r.ok)throw new Error(data.error);toast(data.message);await loadMatchOpinions()}catch(e){toast(e.message||'Não foi possível salvar a nota.')}}
async function loadMatches(manual=false){try{const r=await fetch('/api/matches',{cache:'no-store'}),data=await r.json();if(!r.ok)throw new Error();const previous=state.matches;state.matches=data.matches||[];detectFlamengoGoal(previous,state.matches);renderMatches();if(view==='matches'&&!state.opinionsLoaded)await loadMatchOpinions();$('#matches-updated').textContent=(data.stale?say('Última agenda disponível · ','Latest available fixtures · ','Último calendario disponible · '):say('Agenda atualizada · ','Fixtures updated · ','Calendario actualizado · '))+formatDate(data.updatedAt);if(manual)toast(say('Agenda atualizada.','Fixtures updated.','Calendario actualizado.'))}catch{$('#matches').innerHTML='<div class="empty">'+say('A agenda está temporariamente indisponível.','Fixtures are temporarily unavailable.','El calendario no está disponible temporalmente.')+'</div>';$('#matches-updated').textContent=say('Não foi possível atualizar agora.','Could not update now.','No se pudo actualizar ahora.')}}
$('#reload-matches').onclick=()=>loadMatches(true);
$('#match-focus').onchange=event=>{state.focusedMatch=event.target.value;renderMatchStudio()};$('#rating-match').onchange=event=>{state.ratingMatch=event.target.value;renderRatings()};
if($('#goal-sound'))$('#goal-sound').onclick=async()=>{state.goalSound=!state.goalSound;localStorage.setItem('nrn-goal-sound',state.goalSound?'on':'off');syncGoalSound();if(state.goalSound){await playGoalSound().catch(()=>{});toast(say('Som suave de gol ativado.','Soft goal sound enabled.','Sonido suave de gol activado.'))}else toast(say('Som de gol desativado.','Goal sound disabled.','Sonido de gol desactivado.'))};syncGoalSound();
addEventListener('pointerdown',()=>{const AudioEngine=window.AudioContext||window.webkitAudioContext;if(state.goalSound&&AudioEngine){audioContext=audioContext||new AudioEngine();audioContext.resume().catch(()=>{})}},{once:true,passive:true});
if($('#flatv-play'))$('#flatv-play').onclick=()=>{const frame=$('#flatv-frame');frame.classList.add('is-playing');frame.innerHTML='<iframe src="https://www.youtube-nocookie.com/embed/live_stream?channel=UCOa-WaNwQaoyFHLCDk7qKIw&autoplay=1&rel=0&playsinline=1" title="Flamengo TV ao vivo — canal oficial" allow="autoplay; encrypted-media; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>'};
$$('[data-video]').forEach(card=>card.onclick=event=>{event.preventDefault();const id=card.dataset.video;if(!/^[\w-]{11}$/.test(id))return;const dialog=$('#video-player'),frame=$('#video-frame');$('#video-title').textContent=card.dataset.videoTitle||'Momento histórico';$('#video-youtube').href='https://www.youtube.com/watch?v='+id;frame.innerHTML='<iframe src="https://www.youtube-nocookie.com/embed/'+id+'?autoplay=1&rel=0&playsinline=1" title="'+esc(card.dataset.videoTitle||'Vídeo histórico do Flamengo')+'" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';dialog.showModal()});
if($('#video-player'))$('#video-player').addEventListener('close',()=>$('#video-frame').replaceChildren());
if($('#share-portal'))$('#share-portal').onclick=async()=>{const title='Nação Rubro-Negra — notícias, jogos e votação do Flamengo',url=location.origin+(locale==='pt'?'/':'/'+locale);try{if(navigator.share){await navigator.share({title,url});return}}catch(error){if(error.name==='AbortError')return}open('https://wa.me/?text='+encodeURIComponent(title+' '+url),'_blank','noopener')};
$('#privacy').onclick=()=>location.assign('/privacidade');
const about=document.createElement('a');about.href='/sobre';about.textContent='Sobre o portal';$('#privacy').before(about);
const moderation=document.createElement('a');moderation.href='/admin';moderation.textContent=say('Moderação','Moderation','Moderación');$('#privacy').before(moderation);
$('#ticker-pause').onclick=()=>{const paused=$('.news-wire').classList.toggle('paused');$('#ticker-pause').setAttribute('aria-pressed',String(paused));$('#ticker-pause').textContent=paused?'Continuar':'Pausar'};
function photoError(img){if(!(img instanceof HTMLImageElement))return;if(img.classList.contains('player-photo')){const fallback=document.createElement('span');fallback.className='initials';fallback.textContent=img.dataset.initials||'CRF';img.replaceWith(fallback);return}if(!img.closest('.photo-frame'))return;if(img.dataset.original&&!img.dataset.retried&&img.getAttribute('src').startsWith('/media?')){img.dataset.retried='1';img.src=img.dataset.original;return}const fallback=document.createElement('span');fallback.className='photo-unavailable';fallback.textContent='Foto indisponível · leia na fonte';img.replaceWith(fallback)}
document.addEventListener('error',event=>photoError(event.target),true);
$$('.photo-frame img').filter(img=>img.complete&&!img.naturalWidth).forEach(photoError);
document.addEventListener('click',async event=>{const button=event.target.closest('.share-news');if(!button)return;const url=button.dataset.link,title=button.dataset.title;try{if(navigator.share){await navigator.share({title,url});return}if(navigator.clipboard){await navigator.clipboard.writeText(title+'\n'+url);toast('Link copiado para compartilhar.');return}}catch(error){if(error.name==='AbortError')return}$('#details-content').innerHTML='<span class="eyebrow">COMPARTILHE COM A NAÇÃO</span><h2>'+esc(title)+'</h2><p><a target="_blank" rel="noopener" href="https://wa.me/?text='+encodeURIComponent(title+' '+url)+'">Compartilhar no WhatsApp ↗</a></p><input aria-label="Link da notícia" readonly value="'+esc(url)+'">';setDialog('#details')});
const topButton=document.createElement('button');topButton.className='back-top';topButton.setAttribute('aria-label','Voltar ao início');topButton.innerHTML='<svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="2"><path d="m5 12 7-7 7 7M12 5v15"/></svg>';topButton.hidden=true;topButton.onclick=()=>window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});document.body.append(topButton);window.addEventListener('scroll',()=>topButton.hidden=window.scrollY<700,{passive:true});
if(state.news.length){renderSpotlight();renderAlerts();$('#updated').textContent='Última cópia disponível · '+formatDate(initial.updatedAt);}
let matchRefreshTimer;function scheduleMatchRefresh(){clearTimeout(matchRefreshTimer);const live=state.matches.some(match=>match.state==='in'),next=headlineMatch(),near=next&&next.state!=='post'&&Math.abs(Date.parse(next.date)-Date.now())<7200000,delay=live?15000:near?30000:300000;matchRefreshTimer=setTimeout(async()=>{await loadMatches();scheduleMatchRefresh()},delay)}

const communityState={tab:'opinions',sort:'hot',opinions:[],lineup:[],selectedPlayer:null,loaded:new Set(),ranks:{unpopular:{},lineup:{}},messages:new Map(),lastMessage:0,chatTimer:null};
function randomAlias(){const bytes=new Uint16Array(1);crypto.getRandomValues(bytes);return say('Nação ','Supporter ','Hinchada ')+String(bytes[0]%10000).padStart(4,'0')}
function fanAlias(){let value='';try{value=localStorage.getItem('nrn-alias')||''}catch{}if(value.length<2){value=randomAlias();try{localStorage.setItem('nrn-alias',value)}catch{}}return value.slice(0,24)}
function syncFanAlias(){const button=$('#fan-alias');if(button)button.textContent=fanAlias()+'  ✎'}
function ago(value){const seconds=Math.max(0,Math.floor((Date.now()-Number(value))/1000));if(seconds<45)return say('agora','now','ahora');if(seconds<3600)return Math.floor(seconds/60)+' '+say('min','min','min');if(seconds<86400)return Math.floor(seconds/3600)+' h';return new Intl.DateTimeFormat(intlLocale,{day:'2-digit',month:'short'}).format(new Date(Number(value)))}
function playerFor(id){return state.players.find(player=>player.id===id)}
function opinionCard(row,kind,index){
 const total=Number(row.agree)+Number(row.disagree),agreePct=total?Math.round(Number(row.agree)/total*100):50,previous=communityState.ranks[kind][row.id],rank=index+1,moved=previous&&previous>rank,player=playerFor(row.player),lineup=kind==='lineup';
 const playerLine=player?'<div class="opinion-player">'+playerPhoto(player)+'<span>'+esc(player.name)+'</span></div>':'';
 const body=row.body?'<p class="opinion-body'+(lineup?' is-lineup':'')+'">'+esc(row.body)+'</p>':'<p class="opinion-body is-lineup">'+say('Tem que começar jogando.','Needs to start.','Tiene que ser titular.')+'</p>';
 return '<article class="opinion-card'+(moved?' rank-up':'')+'" data-opinion="'+esc(row.id)+'" style="--agree:'+agreePct+'%;animation-delay:'+Math.min(index*45,360)+'ms"><header class="opinion-author"><span class="fan-avatar">'+esc(initials(row.nickname))+'</span><div><strong>'+esc(row.nickname)+'</strong><time datetime="'+new Date(Number(row.created)).toISOString()+'">'+esc(ago(row.created))+'</time></div><button class="report-content" data-report-kind="opinion" data-report="'+esc(row.id)+'" type="button" aria-label="'+say('Denunciar publicação','Report post','Denunciar publicación')+'">'+say('DENUNCIAR','REPORT','DENUNCIAR')+'</button></header>'+playerLine+body+'<div class="opinion-votes"><button type="button" data-community-vote="agree" aria-pressed="'+String(row.mine==='agree')+'"><span>'+(lineup?say('CONCORDO','AGREE','DE ACUERDO'):say('FAZ SENTIDO','MAKES SENSE','TIENE SENTIDO'))+'</span><b>'+Number(row.agree)+'</b></button><button type="button" data-community-vote="disagree" aria-pressed="'+String(row.mine==='disagree')+'"><span>'+(lineup?say('EU MUDARIA','I’D CHANGE IT','YO CAMBIARÍA'):say('NÃO FAZ','NOT FOR ME','NO TIENE'))+'</span><b>'+Number(row.disagree)+'</b></button></div><div class="opinion-meter"><span>'+(!total?say('Ainda sem votos','No votes yet','Aún sin votos'):agreePct+'% '+(lineup?say('concordam','agree','de acuerdo'):say('acham que faz sentido','say it makes sense','dicen que tiene sentido')))+'</span><span>'+total+' '+say(total===1?'voto':'votos',total===1?'vote':'votes',total===1?'voto':'votos')+'</span></div></article>';
}
function bindOpinionActions(container,kind){
 container.querySelectorAll('[data-community-vote]').forEach(button=>button.onclick=async()=>{const card=button.closest('[data-opinion]');button.disabled=true;try{const r=await fetch('/api/community/vote',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({opinion:card.dataset.opinion,choice:button.dataset.communityVote})}),data=await r.json();if(!r.ok)throw new Error(data.error);await loadCommunity(kind,true)}catch(error){toast(error.message||say('Não foi possível votar.','Could not vote.','No se pudo votar.'))}finally{button.disabled=false}});
 container.querySelectorAll('[data-report]').forEach(button=>button.onclick=()=>reportContent(button.dataset.reportKind,button.dataset.report));
}
function renderCommunity(kind){
 const rows=kind==='lineup'?communityState.lineup:communityState.opinions,feed=$(kind==='lineup'?'#lineup-feed':'#opinions-feed');if(!feed)return;
 feed.innerHTML=rows.length?rows.map((row,index)=>opinionCard(row,kind,index)).join(''):'<div class="opinion-empty"><div><strong>'+say(kind==='lineup'?'ABRA O DEBATE':'MANDE A PRIMEIRA','START THE DEBATE','ABRE EL DEBATE')+'</strong><span>'+say(kind==='lineup'?'Escolha um jogador e defenda sua escalação.':'A primeira opinião impopular pode ser a sua.',kind==='lineup'?'Pick a player and back your lineup.':'The first unpopular opinion can be yours.',kind==='lineup'?'Elige un jugador y defiende tu alineación.':'La primera opinión impopular puede ser la tuya.')+'</span></div></div>';
 communityState.ranks[kind]=Object.fromEntries(rows.map((row,index)=>[row.id,index+1]));bindOpinionActions(feed,kind);
 if(kind==='unpopular'){const votes=rows.reduce((sum,row)=>sum+Number(row.agree)+Number(row.disagree),0);$('#community-stats').textContent=rows.length+' '+say(rows.length===1?'opinião':'opiniões',rows.length===1?'opinion':'opinions',rows.length===1?'opinión':'opiniones')+' · '+votes+' '+say(votes===1?'voto':'votos',votes===1?'vote':'votes',votes===1?'voto':'votos')}
}
async function loadCommunity(kind='unpopular',quiet=false){
 const feed=$(kind==='lineup'?'#lineup-feed':'#opinions-feed');if(!quiet&&!communityState.loaded.has(kind))feed.innerHTML='<div class="loading">'+say('Abrindo a arquibancada…','Opening the stands…','Abriendo la grada…')+'</div>';
 try{const query=new URLSearchParams({kind,sort:kind==='unpopular'?communityState.sort:'hot'}),r=await fetch('/api/community?'+query,{cache:'no-store'}),data=await r.json();if(!r.ok)throw new Error(data.error);if(kind==='lineup')communityState.lineup=data.opinions||[];else communityState.opinions=data.opinions||[];communityState.loaded.add(kind);renderCommunity(kind)}catch(error){feed.innerHTML='<div class="opinion-empty"><div><strong>'+say('ARQUIBANCADA FORA DO AR','STANDS UNAVAILABLE','GRADA NO DISPONIBLE')+'</strong><span>'+esc(error.message||say('Tente novamente em instantes.','Try again shortly.','Inténtalo de nuevo en unos instantes.'))+'</span></div></div>'}
}
async function publishOpinion(kind){
 const status=$(kind==='lineup'?'#lineup-status':'#opinion-status'),button=$(kind==='lineup'?'#lineup-submit':'#opinion-submit'),input=$(kind==='lineup'?'#lineup-take':'#opinion-text'),body=input.value.trim();
 if(kind==='unpopular'&&body.length<8){status.textContent=say('Escreva pelo menos 8 caracteres.','Write at least 8 characters.','Escribe al menos 8 caracteres.');input.focus();return}if(kind==='lineup'&&!communityState.selectedPlayer)return;
 button.disabled=true;status.textContent=say('Publicando…','Posting…','Publicando…');
 try{const r=await fetch('/api/community/opinion',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind,nickname:fanAlias(),body,player:kind==='lineup'?communityState.selectedPlayer:null})}),data=await r.json();if(!r.ok)throw new Error(data.error);input.value='';if(kind==='unpopular')$('#opinion-count').textContent='0';status.textContent=data.message;await loadCommunity(kind,true);toast(data.message)}catch(error){status.textContent=error.message||say('Não foi possível publicar.','Could not post.','No se pudo publicar.')}finally{button.disabled=kind==='lineup'&&!communityState.selectedPlayer}
}
function selectedLineupPlayer(){return playerFor(communityState.selectedPlayer)}
function renderLineupPicks(){
 const target=$('#lineup-picks');if(!target)return;const groups=['Atacante','Meio-campista','Defensor','Goleiro'],picked=[];for(const position of groups)picked.push(...state.players.filter(player=>player.position===position).slice(0,3));for(const player of state.players)if(picked.length<12&&!picked.some(row=>row.id===player.id))picked.push(player);const rows=picked.slice(0,12);
 target.innerHTML=rows.length?rows.map(player=>'<button class="lineup-pick" type="button" data-lineup-player="'+esc(player.id)+'" aria-pressed="'+String(player.id===communityState.selectedPlayer)+'">'+playerPhoto(player)+'<b>'+esc(player.name)+'</b></button>').join(''):'<div class="loading">'+say('Elenco temporariamente indisponível.','Squad temporarily unavailable.','Plantilla temporalmente no disponible.')+'</div>';
 target.querySelectorAll('[data-lineup-player]').forEach(button=>button.onclick=()=>{communityState.selectedPlayer=button.dataset.lineupPlayer;const player=selectedLineupPlayer();$('#lineup-choice').textContent=say('Sua escolha: ','Your pick: ','Tu elección: ')+(player?.name||'');$('#lineup-submit').disabled=false;renderLineupPicks()});
}
function renderLineupDebateHeader(){const next=headlineMatch(),target=$('#lineup-debate-game');if(!target)return;if(!next){target.textContent=say('Escolha um nome e deixe uma frase. Sem formulário demorado.','Pick a player and leave one sentence. No long form.','Elige un jugador y deja una frase. Sin formulario largo.');return}target.textContent=say('Pensando em ','Thinking about ','Pensando en ')+next.home.short+' × '+next.away.short+' · '+matchDate(next.date)}
async function reportContent(kind,content){try{const r=await fetch('/api/community/report',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind,content})}),data=await r.json();if(!r.ok)throw new Error(data.error);toast(data.message)}catch(error){toast(error.message||say('Não foi possível denunciar.','Could not report.','No se pudo denunciar.'))}}
function renderChat(stick=false){
 const feed=$('#chat-feed'),rows=[...communityState.messages.values()].sort((a,b)=>Number(a.created)-Number(b.created)).slice(-80),nearBottom=feed.scrollHeight-feed.scrollTop-feed.clientHeight<90;
 feed.innerHTML=rows.length?rows.map(row=>'<li class="chat-message" data-chat="'+esc(row.id)+'"><span class="fan-avatar">'+esc(initials(row.nickname))+'</span><div><strong>'+esc(row.nickname)+'</strong><p>'+esc(row.body)+'</p></div><time datetime="'+new Date(Number(row.created)).toISOString()+'">'+esc(ago(row.created))+'</time><button class="report-content" data-report-kind="chat" data-report="'+esc(row.id)+'" type="button" aria-label="'+say('Denunciar mensagem','Report message','Denunciar mensaje')+'">⋯</button></li>').join(''):'<li class="opinion-empty"><div><strong>'+say('PUXE O PRIMEIRO CANTO','START THE FIRST CHANT','INICIA EL PRIMER CANTO')+'</strong><span>'+say('A sala começa com a primeira mensagem real.','The room starts with the first real message.','La sala comienza con el primer mensaje real.')+'</span></div></li>';
 feed.querySelectorAll('[data-report]').forEach(button=>button.onclick=()=>reportContent('chat',button.dataset.report));if(stick||nearBottom)requestAnimationFrame(()=>feed.scrollTop=feed.scrollHeight)
}
async function loadChat(manual=false){
 try{const params=communityState.lastMessage?'?after='+Math.max(0,communityState.lastMessage-1):'',r=await fetch('/api/community/chat'+params,{cache:'no-store'}),data=await r.json();if(!r.ok)throw new Error(data.error);for(const message of data.messages||[]){communityState.messages.set(message.id,message);communityState.lastMessage=Math.max(communityState.lastMessage,Number(message.created)||0)}renderChat(manual);$('#chat-status').textContent=say('Atualizado agora · próxima busca em 5 s','Updated now · next check in 5 s','Actualizado ahora · próxima consulta en 5 s')}catch(error){$('#chat-status').textContent=error.message||say('Não foi possível atualizar.','Could not update.','No se pudo actualizar.')}}
async function sendChat(){const input=$('#chat-message'),body=input.value.trim(),button=$('#chat-form button');if(body.length<2)return;button.disabled=true;try{const r=await fetch('/api/community/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({nickname:fanAlias(),body})}),data=await r.json();if(!r.ok)throw new Error(data.error);input.value='';communityState.messages.set(data.message.id,data.message);communityState.lastMessage=Math.max(communityState.lastMessage,Number(data.message.created));renderChat(true)}catch(error){toast(error.message||say('Não foi possível enviar.','Could not send.','No se pudo enviar.'))}finally{button.disabled=false;input.focus()}}
function selectCommunityTab(tab,writeHash=true){
 if(!['opinions','lineup','chat'].includes(tab))tab='opinions';communityState.tab=tab;$$('[data-community-tab]').forEach(button=>button.setAttribute('aria-selected',String(button.dataset.communityTab===tab)));$$('[data-community-pane]').forEach(pane=>pane.hidden=pane.dataset.communityPane!==tab);if(writeHash)history.replaceState(null,'','#'+(tab==='lineup'?'escalacao':tab));
 if(tab==='opinions')loadCommunity('unpopular');if(tab==='lineup'){renderLineupPicks();renderLineupDebateHeader();loadCommunity('lineup')}if(tab==='chat'){loadChat(true);clearInterval(communityState.chatTimer);communityState.chatTimer=setInterval(()=>loadChat(),5000)}else{clearInterval(communityState.chatTimer);communityState.chatTimer=null}
}
function initCommunity(){
 syncFanAlias();const hash=location.hash.slice(1);selectCommunityTab(hash==='escalacao'?'lineup':hash==='chat'?'chat':'opinions',false);
 $$('[data-community-tab]').forEach(button=>button.onclick=()=>selectCommunityTab(button.dataset.communityTab));
 $('#fan-alias').onclick=()=>{$('#alias-input').value=fanAlias();setDialog('#alias-dialog')};$('#alias-form').onsubmit=event=>{event.preventDefault();const value=$('#alias-input').value.replace(/\s+/g,' ').trim().slice(0,24);if(value.length<2)return;try{localStorage.setItem('nrn-alias',value)}catch{}syncFanAlias();setDialog('#alias-dialog',false);toast(say('Apelido salvo.','Nickname saved.','Apodo guardado.'))};
 $('#opinion-text').oninput=event=>$('#opinion-count').textContent=event.target.value.length;$('#opinion-submit').onclick=()=>publishOpinion('unpopular');$('#lineup-submit').onclick=()=>publishOpinion('lineup');
 $$('[data-opinion-sort]').forEach(button=>button.onclick=()=>{communityState.sort=button.dataset.opinionSort;$$('[data-opinion-sort]').forEach(item=>item.setAttribute('aria-pressed',String(item===button)));loadCommunity('unpopular',true)});
 $('#chat-form').onsubmit=event=>{event.preventDefault();sendChat()};$('#chat-refresh').onclick=()=>loadChat(true);addEventListener('hashchange',()=>{const value=location.hash.slice(1);selectCommunityTab(value==='escalacao'?'lineup':value==='chat'?'chat':'opinions',false)});
}

async function boot(){
 if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});loadNews();setInterval(loadNews,300000);
 const needsMatches=['home','matches','community'].includes(view),needsPlayers=['matches','votes','community'].includes(view);let matchTask=Promise.resolve(),playerTask=Promise.resolve();
 if(needsMatches){matchTask=loadMatches();matchTask.finally(scheduleMatchRefresh);setInterval(updateCountdown,1000)}if(needsPlayers)playerTask=loadPlayers();
 if(view==='matches')setInterval(()=>{if(state.opinionsLoaded)loadMatchOpinions()},60000);if(view==='votes'){await playerTask;await loadPolls()}if(view==='groups')loadGroups();if(view==='community'){await Promise.all([matchTask,playerTask]);initCommunity()}
}
boot();
