export const CNN='https://www.cnnbrasil.com.br/esportes/futebol/flamengo/';
export const RSS='https://news.google.com/rss/search?q=Flamengo&hl=pt-BR&gl=BR&ceid=BR:pt-419';
export const ROSTER='https://site.api.espn.com/apis/site/v2/sports/soccer/bra.1/teams/819/roster';
export function text(s=''){return s.replace(/<!\[CDATA\[|\]\]>/g,'').replace(/<[^>]*>/g,'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#0?39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Math.min(+n,1114111))).trim();}
export function safeUrl(s){try{const u=new URL(text(s));return u.protocol==='https:'?u.href:'';}catch{return '';}}
function tag(s,n){return text(s.match(new RegExp('<'+n+'(?:\\s[^>]*)?>([\\s\\S]*?)</'+n+'>','i'))?.[1]||'');}
const NEWS_MAX_AGE=21*86400000;
export function validNewsDate(value,now=Date.now()){const time=Date.parse(value);return Number.isFinite(time)&&time<=now+21600000&&time>=now-NEWS_MAX_AGE;}
export function cnnItems(html){return [...html.matchAll(/<figure\b[\s\S]*?<\/figure>/gi)].map(([s])=>{const a=s.match(/<h2\b[^>]*>[\s\S]*?<a[^>]*href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/i);if(!a)return null;const rawDate=s.match(/datetime="([^"]+)"/i)?.[1],date=rawDate?(rawDate.includes('T')?rawDate:rawDate.replace(' ','T')+'-03:00'):'';return {title:text(a[2]),link:safeUrl(a[1]),source:'CNN Brasil',date,image:safeUrl(s.match(/<img[^>]*(?:src|data-src)="([^"]+)"/i)?.[1]||''),imageAlt:text(s.match(/<img[^>]*alt="([^"]*)"/i)?.[1]||''),imageCredit:'CNN Brasil · fotografia da publicação original'};}).filter(x=>x&&x.link.startsWith(CNN)&&validNewsDate(x.date)).sort((a,b)=>Date.parse(b.date)-Date.parse(a.date)).slice(0,16);}
export function rssItems(xml){return [...xml.matchAll(/<item>([\s\S]*?)<\/item>/gi)].map(([,s])=>{const source=tag(s,'source'),raw=tag(s,'title');return {title:source&&raw.endsWith(' - '+source)?raw.slice(0,-source.length-3):raw,link:safeUrl(tag(s,'link')),source:source||'Google Notícias',date:tag(s,'pubDate'),image:safeUrl(s.match(/<media:(?:content|thumbnail)[^>]*url="([^"]+)"/)?.[1]||''),imageAlt:'',imageCredit:source};}).filter(x=>x.title&&x.link&&validNewsDate(x.date)).sort((a,b)=>Date.parse(b.date)-Date.parse(a.date)).slice(0,30);}
export function rosterItems(data,news=[]){const positions={G:'Goleiro',D:'Defensor',M:'Meio-campista',F:'Atacante'};return (data.athletes||[]).filter(x=>x.status?.type!=='inactive').map(x=>{const profile=safeUrl(x.links?.find(l=>l.rel?.includes('playercard'))?.href||''),matching=news.find(n=>n.image&&([x.displayName,x.lastName].filter(y=>y&&y.length>4).some(y=>n.title.toLowerCase().includes(y.toLowerCase())))&&n.imageAlt.toLowerCase().includes((x.lastName||x.displayName).toLowerCase()));return {id:x.id,name:x.displayName,number:x.jersey||'—',position:positions[x.position?.abbreviation]||x.position?.displayName||'Jogador',age:x.age||null,country:x.citizenship||'',photo:safeUrl(x.headshot?.href||matching?.image||''),photoSource:matching?.link||profile,profile};});}
export function officialRosterItems(raw,cached=[]){const html=raw.replaceAll('\\"','"'),broad=value=>value==='Goleiro'?'Goleiro':/Zagueiro|Lateral/.test(value)?'Defensor':/Volante|Meio/.test(value)?'Meio-campista':'Atacante',norm=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,''),slug=value=>String(value||'jogador').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');const re=/\{"name":"([^"]+)","lastname":[\s\S]{0,100}?"position":"([^"]+)",[\s\S]{0,200}?"number":(null|\d+),[\s\S]{0,160}?"slug":"([^"]+)",[\s\S]{0,180}?"photo":\{[\s\S]{0,150}?"url":"(https:[^"]+)/g;return [...new Map([...html.matchAll(re)].map(match=>{const name=match[1],saved=cached.find(player=>norm(player.name)===norm(name));return [name,{id:saved?.id||'crf-'+slug(name),name,number:match[3]==='null'?'—':match[3],position:broad(match[2]),role:match[2],age:saved?.age||null,country:saved?.country||'',photo:saved?.photo||safeUrl(match[5]),photoSource:'https://www.flamengo.com.br/futebol/elenco',profile:'https://www.flamengo.com.br/futebol/atleta/'+match[4]}];})).values()].filter(player=>player.name!=='Everton Cebolinha');}
export function officialMatches(html){const re=/data-analytics-promotion-name="([^"]+)"[\s\S]{0,400}?data-analytics-promotion-competition="([^"]+)"[\s\S]{0,300}?data-analytics-promotion-match-date="(\d{4}-\d{2}-\d{2})"[\s\S]{0,500}?data-analytics-match-state="([^"]+)"[\s\S]{0,300}?data-analytics-match-date="[^"]*?(\d{2}:\d{2})"[\s\S]{0,200}?data-analytics-match-venue="([^"]*)"[\s\S]*?<\/article>/g;const rows=[];for(const match of html.matchAll(re)){const [homeName,awayName]=match[1].split(/-(?=[^-]+$)/);if(!homeName||!awayName)continue;const block=match[0],homeScore=text(block.match(/teamScoreHome[^>]*>([\s\S]*?)<\/span>/)?.[1]||''),awayScore=text(block.match(/teamScoreAway[^>]*>([\s\S]*?)<\/span>/)?.[1]||''),state=match[4]==='finished'?'post':match[4]==='live'?'in':'pre',date=match[3]+'T'+match[5]+':00-03:00',id=(match[3]+'-'+match[1]).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-');rows.push({id,date,name:match[1].replace('-', ' x '),competition:text(match[2]),status:state==='post'?'Encerrado':state==='in'?'Ao vivo':text(match[6])||'Agendado',state,home:{name:text(homeName),short:'',logo:'',score:homeScore},away:{name:text(awayName),short:'',logo:'',score:awayScore}});}return [...new Map(rows.map(row=>[row.id,row])).values()].sort((a,b)=>Date.parse(a.date)-Date.parse(b.date));}
export function mergeNews(groups){const map=new Map();for(const x of groups.flat().filter(item=>validNewsDate(item.date))){const key=x.title.toLocaleLowerCase('pt-BR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');if(!map.has(key)||(!map.get(key).image&&x.image))map.set(key,x);}return [...map.values()].sort((a,b)=>Date.parse(b.date)-Date.parse(a.date)).slice(0,30);}
