export const ORIGIN='https://nacao-rubro-negra.bryansouzarodrigues0.chatgpt.site';
export const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const e=escapeHtml;
export function imageUrl(value){if(!value)return '';try{const u=new URL(value);if(u.protocol!=='https:')return '';return ['admin.cnnbrasil.com.br','a.espncdn.com'].includes(u.hostname)?'/media?src='+encodeURIComponent(value):value;}catch{return '';}}
export function picture(item,hero=false){const image=imageUrl(item.image);return '<div class="photo-frame'+(hero?' hero-photo':'')+'">'+(image?'<img '+(hero?'loading="eager" fetchpriority="high"':'loading="lazy"')+' decoding="async" width="840" height="500" src="'+e(image)+'" data-original="'+e(item.image)+'" alt="'+e(item.imageAlt||item.title)+'">':'<span class="photo-unavailable">Fotografia não fornecida pela fonte</span>')+'</div>';}
export function dateLabel(value){const d=new Date(value);return Number.isNaN(+d)?'Data não informada':new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'America/Sao_Paulo'}).format(d);}
export function newsSlug(n){return String(n.title||'noticia').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,90);}
export function newsPath(n){return '/noticia/'+newsSlug(n);}
export function renderCard(n){return '<article class="news-card"><a href="'+e(newsPath(n))+'"><div class="news-media">'+picture(n)+'<small>'+e(n.imageCredit||n.source)+'</small></div><div class="news-meta"><b>'+e(n.source)+'</b><time datetime="'+e(n.date)+'">'+e(dateLabel(n.date))+'</time></div><h3>'+e(n.title)+'</h3><span class="read-source">Ver página da notícia →</span></a><button class="share-news" data-link="'+e(ORIGIN+newsPath(n))+'" data-title="'+e(n.title)+'" aria-label="Compartilhar notícia">Compartilhar ↗</button></article>';}
export function renderHero(n){if(!n)return '<p class="empty">Novas publicações em breve.</p>';return '<a href="'+e(newsPath(n))+'">'+picture(n,true)+'<div class="hero-copy"><span class="label">DESTAQUE · '+e(n.source)+'</span><h2>'+e(n.title)+'</h2><small>'+e(dateLabel(n.date))+' · Ver página da notícia →</small></div></a>';}
export const pages={
 '/sobre':{title:'Sobre o portal Nação Rubro-Negra',description:'Conheça o portal independente da torcida do Flamengo, suas fontes e o funcionamento das enquetes, comunidade e grupos.',body:'<span class="eyebrow">FEITO PARA A TORCIDA</span><h1>PAIXÃO PELO FLA.<br>RESPEITO À INFORMAÇÃO.</h1><p>O Nação Rubro-Negra reúne notícias, jogos, memória, votações, conversa entre torcedores e grupos do Flamengo. É um portal independente, sem vínculo oficial com o Clube de Regatas do Flamengo.</p><h2>Notícias e fontes</h2><p>As manchetes apontam para os veículos responsáveis pela publicação. As fotografias, quando disponíveis, pertencem às respectivas fontes. A leitura completa acontece no site original. A central verifica novidades a cada cinco minutos enquanto a página está aberta; horários indicam a última consulta, não uma garantia de cobertura em tempo real.</p><h2>A opinião da arquibancada</h2><p>Enquetes e debates mostram participações recebidas pelo portal. São manifestações espontâneas e não representam pesquisa científica. Um cookie limita algumas ações por navegador; não há verificação de identidade.</p><h2>Moderação da comunidade</h2><p>Opiniões, escolhas de escalação e mensagens são publicadas com apelido. Links são bloqueados, há limite de frequência e qualquer pessoa pode denunciar conteúdo. Publicações com várias denúncias saem do ar para revisão.</p><h2>Grupos da Nação</h2><p>Os grupos são administrados por terceiros. O cadastro fica pendente até revisão. A presença de um grupo no diretório não implica vínculo com o clube.</p><h2>Publicidade</h2><p>Os espaços indicados como publicidade estão reservados. A presença desses espaços não significa que anúncios já estejam ativos.</p>'},
 '/privacidade':{title:'Privacidade e dados — Nação Rubro-Negra',description:'Saiba como o portal utiliza cookies de votação, mensagens da comunidade, preferências de avisos e dados de grupos.',body:'<span class="eyebrow">TRANSPARÊNCIA COM A NAÇÃO</span><h1>PRIVACIDADE<br>E DADOS.</h1><p>Esta página descreve os recursos presentes no portal.</p><h2>Votos e comunidade</h2><p>Um identificador aleatório é guardado em cookie por até um ano. O servidor registra esse identificador junto a votos, opiniões, escolhas de escalação, mensagens, denúncias e horários. O apelido escolhido fica visível nas publicações; não informe nome completo, telefone ou outro dado pessoal. Limpar o cookie cria uma nova identificação neste navegador.</p><h2>Preferências deste aparelho</h2><p>O navegador guarda o apelido da arquibancada, quais manchetes foram vistas e a preferência do som de gol. A abertura de 0,90 segundo é exibida ao entrar pela página inicial, exceto quando o aparelho solicita redução de movimento. As notificações dependem de permissão concedida no aparelho e podem ser revogadas nas configurações do navegador.</p><h2>Grupos enviados</h2><p>Nome, região, categoria, descrição, link e data do cadastro são armazenados para revisão. Após aprovação, os dados do grupo ficam visíveis no diretório. Evite enviar informações pessoais na descrição.</p><h2>Serviços externos</h2><p>Notícias, retratos, vídeos, fontes tipográficas e links de WhatsApp envolvem serviços externos. Ao abrir uma matéria, reproduzir um vídeo ou entrar em um grupo, aplicam-se as regras do serviço responsável. Imagens podem ser entregues pelo portal com cache temporário ou diretamente pelo veículo de origem.</p><h2>Publicidade</h2><p>Esta versão tem posições reservadas e não inclui código de anúncios ou medição publicitária. A ativação desses serviços exigirá a atualização desta página.</p>'}
};
pages['/historia']={title:'História e conquistas do Flamengo | Nação Rubro-Negra',description:'Uma linha do tempo rubro-negra com o Mundial de 1981, Libertadores e momentos que atravessaram gerações.',body:'<span class="eyebrow">MEMÓRIA RUBRO-NEGRA</span><h1>GERAÇÕES<br>DE GLÓRIA.</h1><p>Uma seleção editorial de marcos do futebol do Flamengo. As conquistas abaixo podem ser conferidas na relação oficial de títulos do clube.</p><div class="history-ledger"><article><b>1981</b><h2>O ANO ETERNO</h2><p>Libertadores e Mundial Interclubes colocaram a geração de Zico no ponto mais alto do futebol internacional.</p></article><article><b>2009</b><h2>O HEXA</h2><p>Uma arrancada que terminou com o título brasileiro diante de um Maracanã tomado pela Nação.</p></article><article><b>2019</b><h2>UMA TARDE EM LIMA</h2><p>Dois gols nos minutos finais viraram a decisão e encerraram uma espera de 38 anos pela Libertadores.</p></article><article><b>2022</b><h2>AMÉRICA OUTRA VEZ</h2><p>Campanha invicta e vitória sobre o Athletico-PR na final em Guayaquil.</p></article><article><b>2025</b><h2>O TETRA CONTINENTAL</h2><p>O Flamengo conquistou sua quarta Libertadores, somando o título aos de 1981, 2019 e 2022.</p></article></div><h2>Ídolos de eras diferentes</h2><p>Zico representa a geração campeã do mundo. Júnior atravessou épocas como liderança e técnica. Leandro marcou seu nome como um dos grandes laterais da história. Na era recente, nomes como Bruno Henrique e Arrascaeta construíram trajetórias de títulos e decisões.</p><p><a class="external" target="_blank" rel="noopener" href="https://www.flamengo.com.br/clube/titulos">Conferir os títulos no site oficial do Flamengo ↗</a></p>'};
export function metadata(path='/',title='Flamengo: notícias, enquetes e grupos | Nação Rubro-Negra',description='Notícias do Flamengo com fontes, enquetes do elenco, grupos de torcedores e momentos históricos. Acompanhe o giro rubro-negro.',locale='pt',alternatePaths=null){
 const languages={pt:{lang:'pt-BR',og:'pt_BR',path:'/'},en:{lang:'en',og:'en_US',path:'/en'},es:{lang:'es',og:'es_ES',path:'/es'}},language=languages[locale]||languages.pt,url=ORIGIN+path,logo='https://a.espncdn.com/i/teamlogos/soccer/500/819.png';
 const alternates=alternatePaths?['<link rel="alternate" hreflang="pt-BR" href="'+ORIGIN+alternatePaths.pt+'">','<link rel="alternate" hreflang="en" href="'+ORIGIN+alternatePaths.en+'">','<link rel="alternate" hreflang="es" href="'+ORIGIN+alternatePaths.es+'">','<link rel="alternate" hreflang="x-default" href="'+ORIGIN+alternatePaths.pt+'">'].join(''):'';
 const schema={'@context':'https://schema.org','@graph':[{'@type':'WebSite','@id':ORIGIN+'/#website',name:'Nação Rubro-Negra',alternateName:'NRN',url:ORIGIN+'/',inLanguage:['pt-BR','en','es'],description:'Portal independente de torcedores do Flamengo',publisher:{'@id':ORIGIN+'/#publisher'}},{'@type':'Organization','@id':ORIGIN+'/#publisher',name:'Nação Rubro-Negra',url:ORIGIN+'/',logo:{'@type':'ImageObject',url:logo},description:'Portal independente de torcedores, sem vínculo oficial com o Clube de Regatas do Flamengo.'},{'@type':'CollectionPage','@id':url+'#page',url,name:title,description,inLanguage:language.lang,isPartOf:{'@id':ORIGIN+'/#website'}}]};
 return '<title>'+e(title)+'</title><meta name="description" content="'+e(description)+'"><meta name="author" content="Nação Rubro-Negra"><meta name="referrer" content="strict-origin-when-cross-origin"><meta name="format-detection" content="telephone=no"><link rel="canonical" href="'+e(url)+'">'+alternates+'<meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1"><meta name="googlebot" content="index,follow,max-image-preview:large"><meta property="og:type" content="website"><meta property="og:locale" content="'+language.og+'"><meta property="og:site_name" content="Nação Rubro-Negra"><meta property="og:title" content="'+e(title)+'"><meta property="og:description" content="'+e(description)+'"><meta property="og:url" content="'+e(url)+'"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="'+e(title)+'"><meta name="twitter:description" content="'+e(description)+'"><link rel="manifest" href="/manifest.webmanifest"><script type="application/ld+json">'+JSON.stringify(schema).replace(/</g,'\\u003c')+'</script>';
}
export function decorateHead(html,head){return html.replace(/<title>[\s\S]*?<\/title>/,'').replace(/<meta name="description"[^>]*>/,'').replace('</head>',head+'</head>');}
export function renderInfo(path,style){const info=pages[path];return '<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#df001b">'+metadata(path,info.title,info.description)+'<link rel="icon" href="https://a.espncdn.com/i/teamlogos/soccer/500/819.png"><style>'+style+'</style></head><body><div class="topline">NAÇÃO RUBRO-NEGRA · PORTAL INDEPENDENTE</div><main class="wrap info-page"><a href="/">← Voltar ao portal</a>'+info.body+'<p><a href="/sobre">Sobre</a> · <a href="/privacidade">Privacidade</a></p></main></body></html>';}
export function renderNewsPage(n,style){const path=newsPath(n),description='Manchete publicada por '+n.source+'. Confira os dados da publicação e acesse a matéria completa no veículo original.';const head=metadata(path,n.title+' | Nação Rubro-Negra',description).replace('<meta property="og:url"',n.image?'<meta property="og:image" content="'+e(n.image)+'"><meta name="twitter:image" content="'+e(n.image)+'"><meta property="og:url"':'<meta property="og:url"');return '<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#df001b">'+head+'<link rel="icon" href="https://a.espncdn.com/i/teamlogos/soccer/500/819.png"><style>'+style+'</style></head><body><div class="topline">NAÇÃO RUBRO-NEGRA · PORTAL INDEPENDENTE</div><main class="wrap info-page news-page"><a href="/noticias">← Voltar às notícias</a><span class="eyebrow">'+e(n.source)+' · '+e(dateLabel(n.date))+'</span><h1>'+e(n.title)+'</h1>'+picture(n)+'<p>'+e(description)+'</p><p><a class="primary external" target="_blank" rel="noopener" href="'+e(n.link)+'">LER A MATÉRIA NA FONTE ORIGINAL ↗</a></p><p class="small">O Nação Rubro-Negra organiza a manchete e direciona a leitura ao veículo responsável. O conteúdo integral não é reproduzido aqui.</p></main></body></html>';}
