import {ORIGIN} from './editorial.mjs';
export const memoryPaths=['/idolos','/idolos/zico','/idolos/junior','/idolos/leandro'];
const vids=[['FJrr1KR3GQE','Zico conta histórias de suas cobranças de falta','Flamengo TV'],['1f2KBj4lJ0I','Sávio reage a um gol histórico de Zico','Canal Zico 10'],['zpIz3YeOLs8','A volta de Zico ao Flamengo','Flamengo TV']];
const idols={zico:['Zico','O Galinho','Símbolo da geração campeã da Libertadores e do Mundial de 1981. Marcou uma era com técnica, liderança e identificação com a torcida.'],junior:['Júnior','Maestro da lateral','Versatilidade e inteligência em duas passagens históricas. Participou das maiores conquistas da geração de 1981.'],leandro:['Leandro','Elegância rubro-negra','Construiu toda a carreira profissional no Flamengo e integrou a geração campeã do mundo em 1981.']};
const style=`body{margin:0;background:#080608;color:#fff;font-family:Inter,Arial}.head{display:flex;justify-content:space-between;padding:20px 5vw;background:#13070b;border-bottom:1px solid #8b1d34}.head a,a{color:#fff;text-decoration:none;font-weight:900}.head nav{display:flex;gap:20px}.memory{max-width:1180px;margin:auto;padding:70px 22px}.eyebrow{color:#ff4565;font-weight:900;letter-spacing:.15em}.memory h1{font:900 clamp(55px,10vw,115px)/.84 Arial;margin:22px 0}.memory h1 em{color:#ed0030}.lead{max-width:760px;color:#e2b8c1;font-size:19px;line-height:1.6}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:38px}.card{background:linear-gradient(145deg,#370913,#10070a);border:1px solid #732039;border-radius:24px 7px;overflow:hidden}.card img{width:100%;aspect-ratio:16/9;object-fit:cover}.card button{position:relative;width:100%;padding:0;border:0;background:#24070d;color:#fff;cursor:pointer}.play{position:absolute;inset:0;display:grid;place-items:center;font-size:44px}.copy,.idol{display:block;padding:22px}.copy small,.idol b{color:#ff5875}.tools input{width:min(600px,90%);margin-top:30px;padding:15px;background:#1c0b10;color:#fff;border:1px solid #7d2639;border-radius:14px}iframe{width:100%;aspect-ratio:16/9;border:0}@media(max-width:760px){.grid{grid-template-columns:1fr}.memory h1{font-size:58px}}`;
const shell=(t,d,c)=>`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta name="description" content="${d}"><meta name="theme-color" content="#df001b"><link rel="canonical" href="${ORIGIN}"><title>${t} · Nação Rubro-Negra</title><style>${style}</style></head><body><header class="head"><a href="/">← NAÇÃO</a><nav><a href="/videos">VÍDEOS</a><a href="/idolos">ÍDOLOS</a></nav></header><main>${c}</main></body></html>`;
const cards=()=>vids.map(v=>`<article class="card" data-search="${v.join(' ').toLowerCase()}"><button data-video="${v[0]}"><img loading="lazy" src="https://i.ytimg.com/vi/${v[0]}/hqdefault.jpg" alt="${v[1]}"><span class="play">▶</span></button><div class="copy"><small>${v[2]}</small><h2>${v[1]}</h2></div></article>`).join('');
const script=`<script>q?.addEventListener('input',()=>document.querySelectorAll('.card').forEach(c=>c.hidden=!c.dataset.search.includes(q.value.toLowerCase())));document.addEventListener('click',e=>{let b=e.target.closest('[data-video]');if(!b)return;let f=document.createElement('iframe');f.src='https://www.youtube-nocookie.com/embed/'+b.dataset.video+'?autoplay=1';f.allow='autoplay; encrypted-media; picture-in-picture';f.allowFullscreen=true;b.replaceWith(f)})</script>`;
export function renderMemory(p){if(p==='/videos')return shell('Arquivo em vídeo','Vídeos históricos do Flamengo em canais de origem.',`<section class="memory"><span class="eyebrow">A MEMÓRIA TEM REPLAY</span><h1>ARQUIVO<br><em>RUBRO-NEGRO.</em></h1><p class="lead">Relatos e imagens históricas. O vídeo só é carregado quando você escolhe assistir.</p><div class="tools"><input id="q" type="search" placeholder="Buscar no arquivo…"></div><div class="grid">${cards()}</div></section>${script}`);if(p==='/idolos')return shell('Ídolos','Perfis de ídolos do Flamengo.',`<section class="memory"><span class="eyebrow">QUEM FEZ A HISTÓRIA</span><h1>ÍDOLOS<br><em>ETERNOS.</em></h1><div class="grid">${Object.entries(idols).map(([s,x])=>`<a class="card idol" href="/idolos/${s}"><b>${x[1]}</b><h2>${x[0]}</h2><p>${x[2]}</p><strong>ABRIR PERFIL →</strong></a>`).join('')}</div></section>`);let x=idols[p.split('/').pop()];return x?shell(x[0],x[2],`<article class="memory"><span class="eyebrow">${x[1]}</span><h1>${x[0]}<em>.</em></h1><p class="lead">${x[2]}</p>${x[0]==='Zico'?'<div class="grid">'+cards()+'</div>'+script:''}<p><a href="https://www.flamengo.com.br/clube/titulos" target="_blank">Fonte oficial →</a></p></article>`):null}
